### ISSUE TITLE
CSharpSymbolDeclaredEventAnalyzer and BasicSymbolDeclaredEventAnalyzer crashes in recent VS "15" builds

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-analyzers#1043]
In recent VS "15" builds, opening the project system solution causes both CSharpSymbolDeclaredEventAnalyzer and BasicSymbolDeclaredEventAnalyzer to crash:

```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Error	AD0001	Analyzer 'Roslyn.Diagnostics.Analyzers.CSharp.CSharpSymbolDeclaredEventAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'Sequence contains no elements'.	Microsoft.VisualStudio.ProjectSystem.Managed		1	Active	Analyzer 'Roslyn.Diagnostics.Analyzers.CSharp.CSharpSymbolDeclaredEventAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: Microsoft.VisualStudio.ProjectSystem.Managed

System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Roslyn.Diagnostics.Analyzers.SymbolDeclaredEventAnalyzer`1.CompilationAnalyzer..ctor(INamedTypeSymbol symbolType, INamedTypeSymbol compilationType)
   at Roslyn.Diagnostics.Analyzers.CSharp.CSharpSymbolDeclaredEventAnalyzer.GetCompilationAnalyzer(Compilation compilation, INamedTypeSymbol symbolType)
   at Roslyn.Diagnostics.Analyzers.SymbolDeclaredEventAnalyzer`1.<Initialize>b__7_0(CompilationStartAnalysisContext compilationContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass33_0.<ExecuteCompilationStartActions>b__0()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info)
-----

```

```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Error	AD0001	Analyzer 'Roslyn.Diagnostics.Analyzers.VisualBasic.BasicSymbolDeclaredEventAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'Sequence contains no elements'.	Microsoft.VisualStudio.AppDesigner		1	Active	Analyzer 'Roslyn.Diagnostics.Analyzers.VisualBasic.BasicSymbolDeclaredEventAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: Microsoft.VisualStudio.AppDesigner

System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Roslyn.Diagnostics.Analyzers.SymbolDeclaredEventAnalyzer`1.CompilationAnalyzer..ctor(INamedTypeSymbol symbolType, INamedTypeSymbol compilationType)
   at Roslyn.Diagnostics.Analyzers.VisualBasic.BasicSymbolDeclaredEventAnalyzer.GetCompilationAnalyzer(Compilation compilation, INamedTypeSymbol symbolType)
   at Roslyn.Diagnostics.Analyzers.SymbolDeclaredEventAnalyzer`1.<Initialize>b__7_0(CompilationStartAnalysisContext compilationContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass33_0.<ExecuteCompilationStartActions>b__0()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info)
-----
'.

```

I have no idea what these analyzers do, so I don't know what the code it's choking on - but it appears to be failing for nearly all projects.

**Comment by mavasani** [comment]
This analyzer is primarily meant for C# and VB compiler projects in Roslyn.sln - it checks that source symbol implementations of `ISymbol` generated Symbol declared event, which in turn ensures the analyzer driver invokes analyzer symbol actions for these symbols.

The analyzer is [disabled by default](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Roslyn.Diagnostics.Analyzers/Core/SymbolDeclaredEventMustBeGeneratedForSourceSymbols.cs#L30), and only explicitly turned on for C# and VB compiler projects in Roslyn.sln via a ruleset specific to these projects.

@davkean - the fix here is to ensure that we don't turn on [RS0019](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Roslyn.Diagnostics.Analyzers/Core/RoslynDiagnosticIds.cs#L25) reported by this analyzer for project system solution.

**Comment by mavasani** [comment]
Tagging @srivatsn - I don't see any ruleset in project system repo that seems to be turning this rule on. Given that Dave mentions this repros only in Dev15, is it likely that we are executing even disabled analyzers on Dev15? Can you quickly check on latest Dev15 builds by writing a simple analyzer that is turned off by default and installed for a managed project?

**Comment by srivatsn** [comment]
The project system repo has a problem with the way analyzers are being configured. The targets are pulling in analyzers if they happen to exist in the packages directory even though they are not included in the dependencies explicitly. I'm looking at fixing that.

**Comment by davkean** [comment]
It's by design that these crash? I don't understand that.

**Comment by mavasani** [comment]
Analyzer is written to be run only for C# and VB compiler projects - it is disabled by default, so they should never be turned on for any other project
