### ISSUE TITLE
Analyzer 'System.Runtime.Analyzers.CallGCSuppressFinalizeCorrectlyAnalyzer' threw an exception of type 'System.NullReferenceException' 

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#1050]
#### Analyzer package

System.Runtime.Analyzers

#### Analyzer

CallGCSuppressFinalizeCorrectlyAnalyzer

#### Repro steps

I see the following AD0001 in IDE when opening Roslyn.sln:

```
Severity	Code	Description	Project	File	Line	Source	Tool	Suppression State	Detail Description
Error	AD0001	Analyzer 'System.Runtime.Analyzers.CallGCSuppressFinalizeCorrectlyAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	TestUtilities		1	IntelliSense	System.Runtime.Analyzers	Active	Analyzer 'System.Runtime.Analyzers.CallGCSuppressFinalizeCorrectlyAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: Roslyn.Test.Utilities

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Runtime.Analyzers.CallGCSuppressFinalizeCorrectlyAnalyzer.<>c.<Initialize>b__13_0(CompilationStartAnalysisContext compilationContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass33_0.<ExecuteCompilationStartActions>b__0()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info)
-----
'.
```

**Comment by heejaechang** [comment]
what do you expect it to show?

**Comment by mavasani** [comment]
Line numbers for the call stack? I remember we used to see them before

**Comment by heejaechang** [comment]
I just checked, this code just show diagnostic reported by compiler. so this should be exactly same as v1.

so, if line number is not there, then, there is no line number before.

**Comment by heejaechang** [comment]
oops comment in wrong issue.
