### ISSUE TITLE
[CI Failure] SocketException thrown while downloading vswhere

### ISSUE THREAD

**Issue by jamesqo** [dotnet/roslyn-analyzers#1289]
I'm opening this after repeated CI failures during my PR at #1283. Here's the output CI generates if I put `Write-Host "Downloading vswhere..."` just before the `Invoke-WebRequest` to download it in `Build.ps1`:

```
19:39:11 Downloading vswhere...
19:39:54 Unable to connect to the remote server
19:39:54 System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 192.30.255.112:80
19:39:54    at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
19:39:54    at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
19:39:54    --- End of inner exception stack trace ---
19:39:54    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
19:39:54    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
19:39:54 at LocateMsbuild, D:\j\workspace\windows_debug---c729d7ab\build\Build.ps1: line 52
19:39:54 at Build, D:\j\workspace\windows_debug---c729d7ab\build\Build.ps1: line 67
19:39:54 at <ScriptBlock>, D:\j\workspace\windows_debug---c729d7ab\build\Build.ps1: line 113
19:39:54 at <ScriptBlock>, <No file>: line 1
19:39:54 Killing running build processes...
```

[failure 1](https://ci.dot.net/job/dotnet_roslyn-analyzers/job/master/job/windows_debug_prtest/254/console), [failure 2](https://ci.dot.net/job/dotnet_roslyn-analyzers/job/master/job/windows_debug_prtest/254/console)

**Comment by 333fred** [comment]
Appears to have resolved itself, this was a github issue.
