### ISSUE TITLE
SerializationRulesDiagnosticAnalyzer crashing in Project System

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn-analyzers#1290]
Analyzer 'Microsoft.NetFramework.Analyzers.SerializationRulesDiagnosticAnalyzer' threw an exception of type `System.ArgumentException` with message "Reported diagnostic with ID `CA2235` is not supported by the analyzer."

Exception occurred with following context:
**Compilation:** Microsoft.VisualStudio.AppDesigner
**ISymbol:** MultipleValuesStore (NamedType)

```
System.ArgumentException: Reported diagnostic with ID 'CA2235' is not supported by the analyzer.
Parameter name: diagnostic
   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalysisContextHelpers.VerifyArguments(Diagnostic diagnostic, Compilation compilationOpt, Func`2 isSupportedDiagnostic)
   at Microsoft.CodeAnalysis.Diagnostics.SymbolAnalysisContext.ReportDiagnostic(Diagnostic diagnostic)
   at Microsoft.NetFramework.Analyzers.SerializationRulesDiagnosticAnalyzer.SymbolAnalyzer.AnalyzeSymbol(SymbolAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteSymbolActionsCore>b__38_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
```

**Comment by mavasani** [comment]
We already report CA2235 as a supported diagnostic: https://github.com/dotnet/roslyn-analyzers/blob/4e298f6afd156d5e958d21be8afe2c3cc99fdea3/src/Microsoft.NetFramework.Analyzers/Core/SerializationDiagnosticAnalyzer.cs#L89. This should not repro anymore, please re-activate if you can repro.
