### ISSUE TITLE
CA1825 AvoidZeroLengthARrayAllocationsFixer throws NullReferenceException

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/roslyn-analyzers#1298]
#### Analyzer package

Microsoft.CodeAnalysis.FxCopAnalyzers (2.3.0-beta1)

#### Analyzer

AvoidZeroLengthArrayALlocationsFixer

#### Repro steps

```csharp
private static readonly IReadOnlyCollection<ApiDefinition> s_emptySearchResults = new ApiDefinition[] { };
```

#### Expected behavior

Replace with `Array.Empty<ApiDefinition>()`

#### Actual behavior

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.Kind(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.GetType(SyntaxNode declaration)
   at async Microsoft.NetCore.Analyzers.Runtime.AvoidZeroLengthArrayAllocationsFixer.ConvertToArrayEmpty(<Unknown Parameters>)
   at async Microsoft.NetCore.Analyzers.Runtime.AvoidZeroLengthArrayAllocationsFixer.<>c__DisplayClass3_0.<RegisterCodeFixesAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputePreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by jamesqo** [comment]
I'll grab this issue.

**Comment by jamesqo** [comment]
I did a little bit of investigating: part of the reason why it's not working is [this Roslyn issue](https://github.com/dotnet/roslyn/issues/23017). However, this issue isn't blocked, because the approach the fixer takes appears to be wrong in the first place. With

```cs
private static readonly IReadOnlyCollection<ApiDefinition> s_emptySearchResults = new ApiDefinition[] { };
```

it currently tries to look at the type of the variable declaration, `IReadOnlyCollection<ApiDefinition>`, gets the element type of that, and concludes the type is `ApiDefinition`. Instead, it should look at the value of the field, `new ApiDefinition[] { }`, to obtain the element type.

**Comment by jamesqo** [comment]
**From #1337:**

Cause of https://github.com/dotnet/roslyn-analyzers/issues/1298

The fixer should not assume that the `new int[0]` expression is being assigned in a variable declaration of some sort. e.g. It could be passed as an argument to a method call, be passed into an attribute, or used in an assignment that's not a declaration. The element type of the array should also be inferred from the expression itself even if there is a declaration present: in `object[] arr = new string[0]`, we want to replace it with `Array.Empty<string>()`, not `Array.Empty<object>()`.
