### ISSUE TITLE
Null reference exception in Microsoft.NetFramework.Analyzers.SerializationRulesDiagnosticAnalyzer

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#1335]
**Version Used**: Install latest d15rel drop 27031.1.d15rel

**Steps to Reproduce**:

1. git clone https://github.com/JamesNK/Newtonsoft.Json
2. add myget package feed for roslyn-analyzers: https://dotnet.myget.org/F/roslyn-analyzers/api/v3/index.json
3. install latest preview of Microsoft.CodeAnalysis.FxCopAnalyzers version 2.6.0-beta1-62231-02 to all projects in solution
4. enable FSA for C#

Got the following AD0001 diagnostic for NRE in `Microsoft.NetFramework.Analyzers.SerializationRulesDiagnosticAnalyzer`

```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD0001	Analyzer 'Microsoft.NetFramework.Analyzers.SerializationRulesDiagnosticAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	Newtonsoft.Json.Tests(net40)		1	Active	Analyzer 'Microsoft.NetFramework.Analyzers.SerializationRulesDiagnosticAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: Newtonsoft.Json.Tests
ISymbol: IExample (NamedType)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.NetFramework.Analyzers.SerializationRulesDiagnosticAnalyzer.SymbolAnalyzer.AnalyzeSymbol(SymbolAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteSymbolActionsCore>b__38_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.
```

**Comment by mavasani** [comment]
@jinujoseph - needs fixing for 15.5
