### ISSUE TITLE
Test infrastructure says it's using C# 7 but "nameof" is not defined 

### ISSUE THREAD

**Issue by chborl** [dotnet/roslyn-analyzers#1364]
#### Analyzer package

Microsoft.CodeQuality.Analyzers

#### Analyzer

Example: UseNameofInPlaceOfString

#### Repro steps
1. Get unit test file here: \roslyn-analyzers\src\Microsoft.CodeQuality.Analyzers\Core\Maintainability\UseNameofInPlaceOfString.Fixer.cs
2. Remove these parameters `allowNewCompilerDiagnostics: true, validationMode: TestValidationMode.AllowCompileErrors` from the VerifyCSharpFix method
3. Run the tests

#### Expected behavior
Tests should still pass when the test parameters are removed

#### Actual behavior
Tests fail with an error that seems to indicate the version of C# is lower that 6.0.  But looking at the compilation in the debugger, it is C#7 so should not be giving this error.  

```
Microsoft.CodeQuality.Analyzers.Maintainability.UnitTests.UseNameOfInPlaceOfStringTests.Fixer_ArgumentMatchesAParameterInScope FAILED:
	Exception type: 'Xunit.Sdk.TrueException', number: '0', parent: '-1'
	Exception message:
Test contains compilation error(s). Pass TestValidationMode.AllowCompileErrors if these are intended:
Test0.cs(7,41): error CS0103: The name 'nameof' does not exist in the current context
Expected: True
Actual:   False
	Exception stacktrace
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\BooleanAsserts.cs:line 95
   at Xunit.Assert.True(Boolean condition, String userMessage) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\BooleanAsserts.cs:line 83
   at Test.Utilities.DiagnosticExtensions.ValidateNoCompileErrors(ImmutableArray`1 compilerDiagnostics) in C:\Users\chborley\Documents\GitHub\roslyn-analyzers\src\Test.Utilities\DiagnosticExtensions.cs:line 70
   at Test.Utilities.DiagnosticExtensions.GetAnalyzerDiagnostics[TCompilation](TCompilation c, DiagnosticAnalyzer[] analyzers, TestValidationMode validationMode, AnalyzerOptions options, Action`3 onAnalyzerException, Boolean logAnalyzerExceptionAsDiagnostics) in C:\Users\chborley\Documents\GitHub\roslyn-analyzers\src\Test.Utilities\DiagnosticExtensions.cs:line 53
   at Test.Utilities.DiagnosticAnalyzerTestBase.GetSortedDiagnostics(DiagnosticAnalyzer analyzerOpt, Document[] documents, Nullable`1[] spans, TestValidationMode validationMode, IEnumerable`1 additionalFiles) in C:\Users\chborley\Documents\GitHub\roslyn-analyzers\src\Test.Utilities\DiagnosticAnalyzerTestBase.cs:line 416
   at Test.Utilities.CodeFixTestBase.VerifyFix(Document document, DiagnosticAnalyzer analyzerOpt, CodeFixProvider codeFixProvider, String newSource, String newSourceFileName, IEnumerable`1 additionalFiles, Nullable`1 codeFixIndex, Boolean allowNewCompilerDiagnostics, Boolean onlyFixFirstFixableDiagnostic, TestValidationMode validationMode) in C:\Users\chborley\Documents\GitHub\roslyn-analyzers\src\Test.Utilities\CodeFixTestBase.cs:line 120
   at Test.Utilities.CodeFixTestBase.VerifyFix(String language, DiagnosticAnalyzer analyzerOpt, CodeFixProvider codeFixProvider, String oldSource, String newSource, Nullable`1 codeFixIndex, Boolean allowNewCompilerDiagnostics, Boolean onlyFixFirstFixableDiagnostic, TestValidationMode validationMode, Boolean allowUnsafeCode) in C:\Users\chborley\Documents\GitHub\roslyn-analyzers\src\Test.Utilities\CodeFixTestBase.cs:line 46
   at Test.Utilities.CodeFixTestBase.VerifyCSharpFix(String oldSource, String newSource, Nullable`1 codeFixIndex, Boolean allowNewCompilerDiagnostics, Boolean onlyFixFirstFixableDiagnostic, TestValidationMode validationMode) in C:\Users\chborley\Documents\GitHub\roslyn-analyzers\src\Test.Utilities\CodeFixTestBase.cs:line 33
   at Microsoft.CodeQuality.Analyzers.Maintainability.UnitTests.UseNameOfInPlaceOfStringTests.Fixer_ArgumentMatchesAParameterInScope()
```

**Comment by mavasani** [comment]
This is being caused due to Roslyn bug: https://github.com/dotnet/roslyn/issues/24212

I will add a workaround for this in the fixer.
