### ISSUE TITLE
Analyzer driver ArgumentOutOfRangeException exception in Nunit test projects

### ISSUE THREAD

**Issue by nick-kompas** [dotnet/roslyn-analyzers#1560]
#### Analyzer package

Microsoft.CodeQuality.Analyzers, version [2.6.0](https://www.nuget.org/packages/Microsoft.CodeQuality.Analyzers/2.6.0)
![analyzers](https://user-images.githubusercontent.com/22912449/35858113-35fca7e4-0b33-11e8-87f1-4d93389b4992.PNG)

#### Error

```
Analyzer driver threw the following exception:
'System.ArgumentOutOfRangeException: Unexpected SpecialType: '0'.
Parameter name: specialType
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetSpecialType(SpecialType specialType)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.GetDefaultParameterValue(SyntaxNode syntax, ParameterSymbol parameter, ThreeState enableCallerInfo, LocalRewriter localRewriter, Binder binder, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.AppendMissingOptionalArguments(CSharpOperationFactory operationFactory, SyntaxNode syntax, Symbol methodOrIndexer, MethodSymbol optionalParametersMethod, Boolean expanded, Binder binder, ArrayBuilder`1 missingParameters, ArrayBuilder`1 argumentsBuilder)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.BuildArgumentsInEvaluationOrder(CSharpOperationFactory operationFactory, SyntaxNode syntax, Symbol methodOrIndexer, MethodSymbol optionalParametersMethod, Boolean expanded, ImmutableArray`1 argsToParamsOpt, ImmutableArray`1 arguments, Binder binder)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.MakeArgumentsInEvaluationOrder(CSharpOperationFactory operationFactory, Binder binder, SyntaxNode syntax, ImmutableArray`1 arguments, Symbol methodOrIndexer, MethodSymbol optionalParametersMethod, Boolean expanded, ImmutableArray`1 argsToParamsOpt, Boolean invokedAsExtensionMethod)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.DeriveArguments(BoundNode boundNode, Binder binder, Symbol methodOrIndexer, MethodSymbol optionalParametersMethod, ImmutableArray`1 boundArguments, ImmutableArray`1 argumentNamesOpt, ImmutableArray`1 argumentsToParametersOpt, ImmutableArray`1 argumentRefKindsOpt, ImmutableArray`1 parameters, Boolean expanded, SyntaxNode invocationSyntax, Boolean invokedAsExtensionMethod)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.<>c__DisplayClass9_0.<CreateBoundCallOperation>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.CodeAnalysis.Operations.LazyInvocationExpression.get_ArgumentsImpl()
   at Microsoft.CodeAnalysis.Operations.BaseInvocationExpression.<get_Children>d__12.MoveNext()
   at Microsoft.CodeAnalysis.Operations.OperationExtensions.<Descendants>d__3.MoveNext()
   at System.Collections.Immutable.ImmutableArray`1.Builder.AddRange(IEnumerable`1 items)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.GetOperationsToAnalyze(ImmutableArray`1 operationBlocks)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.TryExecuteDeclaringReferenceActions(SyntaxReference decl, Int32 declarationIndex, SymbolDeclaredCompilationEvent symbolEvent, AnalysisScope analysisScope, AnalysisState analysisStateOpt, Boolean shouldExecuteSyntaxNodeActions, Boolean shouldExecuteOperationActions, Boolean shouldExecuteCodeBlockActions, Boolean shouldExecuteOperationBlockActions, Boolean isInGeneratedCode, CancellationToken cancellationToken)
```

#### Repro steps

1. Add Nunit project in solution
2. Problem appears

#### Other details
It appears it was referenced 8 months ago: https://github.com/dotnet/roslyn/issues/20330 but it happens still using version 2.6.0

**Comment by mavasani** [comment]
Thanks, I will try to repro this today- we have been trying hard to get a repro for this stack on the latest bits.

**Comment by mavasani** [comment]
@nick-kompas Do you have a repro solution that you can share? I am unable to repro it by creating a default nunit test project and adding FxCop analyzers nuget reference.

**Comment by mavasani** [comment]
Ping @nick-kompas do you have a repro?

**Comment by mavasani** [comment]
Closing this out as no repro. Kindly re-open if you have a repro or hit again on latest VS2017 builds.
