### ISSUE TITLE
NRE in Microsoft.CodeAnalysis.Operations.DataFlow.NullAnalysis.NullAnalysis.NullDataFlowOperationVisitor.VisitAssignmentOperation

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#1597]
#### Analyzer package

Example: Microsoft.CodeQuality.Analyzers.Exp, version [2.6.1-beta1-62621-02](https://dotnet.myget.org/feed/roslyn-analyzers/package/nuget/Microsoft.CodeQuality.Analyzers.Exp)

#### Analyzer

DisposeObjectsBeforeLosingScope

#### Repro steps
Got the analyzer exception diagnostic AD0001 while dogfooding the experimental package:

```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD0001	Analyzer 'Microsoft.CodeQuality.Analyzers.Exp.Reliability.DisposeObjectsBeforeLosingScope' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	ClassLibrary14		1	Active	Analyzer 'Microsoft.CodeQuality.Analyzers.Exp.Reliability.DisposeObjectsBeforeLosingScope' threw the following exception:
'Exception occurred with following context:
Compilation: ClassLibrary14
ISymbol: Dispose (Method)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.Operations.DataFlow.NullAnalysis.NullAnalysis.NullDataFlowOperationVisitor.VisitAssignmentOperation(IAssignmentOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitSimpleAssignment(ISimpleAssignmentOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.BaseSimpleAssignmentExpression.Accept[TArgument,TResult](OperationVisitor`2 visitor, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitCore(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.Visit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitArray(IEnumerable`1 operations, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.NullAnalysis.NullAnalysis.NullDataFlowOperationVisitor.DefaultVisit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.OperationVisitor`2.VisitLock(ILockOperation operation, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.BaseLockStatement.Accept[TArgument,TResult](OperationVisitor`2 visitor, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitCore(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.Visit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.Flow(IOperation statement, BasicBlock block, TAnalysisData input)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowAnalysis`3.Flow(BasicBlock block, TAnalysisData data)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowAnalysis`3.Run(ControlFlowGraph cfg)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowAnalysis`3.GetOrComputeResultCore(ControlFlowGraph cfg)
   at Microsoft.CodeAnalysis.Operations.DataFlow.NullAnalysis.NullAnalysis.GetOrComputeResult(ControlFlowGraph cfg, INamedTypeSymbol containingTypeSymbol, DataFlowAnalysisResult`2 pointsToAnalysisResultOpt)
   at Microsoft.CodeQuality.Analyzers.Exp.DisposeAnalysisHelper.TryGetOrComputeResult(ImmutableArray`1 operationBlocks, IMethodSymbol containingMethod, Boolean trackInstanceFields, ControlFlowGraph& cfg, DataFlowAnalysisResult`2& disposeAnalysisResult, DataFlowAnalysisResult`2& pointsToAnalysisResult, ImmutableDictionary`2& trackedInstanceFieldPointsToMap)
   at Microsoft.CodeQuality.Analyzers.Exp.Reliability.DisposeObjectsBeforeLosingScope.<>c__DisplayClass7_0.<Initialize>b__1(OperationBlockAnalysisContext operationBlockContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__48`2.<ExecuteBlockActions>b__48_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.

```

**Comment by mavasani** [comment]
Got a repro: happens for invalid code while typing.

```
    public void Dispose()
    {
        A x = new A();
        = x;
    }
```
