### ISSUE TITLE
DisposeObjectsBeforeLosingScope threw "System.InvalidOperationException: Operation is not valid due to the current state of the object."

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-analyzers#1735]
#### Diagnostic ID

DisposeObjectsBeforeLosingScope

#### Repro steps

``` C#
// Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

namespace System.Threading.Tasks
{
    public static class TaskTimeoutExtensions
    {
        public static async Task TimeoutAfter(this Task task, TimeSpan timeout)
        {
            using (var cts = new CancellationTokenSource())
            {
                Task timeoutTask = Task.Delay(timeout, cts.Token);
                Task completedTask = await Task.WhenAny(task, timeoutTask)
                                              .ConfigureAwait(false);

                if (timeoutTask == completedTask)
                    throw new TimeoutException($"Task timed out after {timeout.TotalMilliseconds} ms");

                cts.Cancel();
                await task.ConfigureAwait(false);
            }
        }

        public static async Task<TResult> TimeoutAfter<TResult>(this Task<TResult> task, TimeSpan timeout)
        {
            using (var cts = new CancellationTokenSource())
            {
                Task timeoutTask = Task.Delay(timeout, cts.Token);
                Task completedTask = await Task.WhenAny(task, timeoutTask)
                                              .ConfigureAwait(false);

                if (timeoutTask == completedTask)
                    throw new TimeoutException($"Task timed out after {timeout.TotalMilliseconds} ms");

                cts.Cancel();
                return await task.ConfigureAwait(false);
            }
        }
    }
}

```

```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Error	AD0001	Analyzer 'Microsoft.CodeQuality.Analyzers.Exp.Reliability.DisposeObjectsBeforeLosingScope' threw an exception of type 'System.InvalidOperationException' with message 'Operation is not valid due to the current state of the object.'.	Microsoft.VisualStudio.ProjectSystem.Managed.TestServices		1	Active	Analyzer 'Microsoft.CodeQuality.Analyzers.Exp.Reliability.DisposeObjectsBeforeLosingScope' threw the following exception:
'Exception occurred with following context:
Compilation: Microsoft.VisualStudio.ProjectSystem.Managed.TestServices
ISymbol: TimeoutAfter (Method)

System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.GetCachedAbstractValue(IOperation operation)
   at Microsoft.CodeAnalysis.Operations.DataFlow.PointsToAnalysis.PointsToAnalysis.PointsToDataFlowOperationVisitor.VisitObjectOrCollectionInitializer(IObjectOrCollectionInitializerOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.BaseObjectOrCollectionInitializerExpression.Accept[TArgument,TResult](OperationVisitor`2 visitor, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitCore(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.Visit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitArray(IEnumerable`1 operations, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.PointsToAnalysis.PointsToAnalysis.PointsToDataFlowOperationVisitor.DefaultVisit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.OperationVisitor`2.VisitInvalid(IInvalidOperation operation, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.BaseInvalidOperation.Accept[TArgument,TResult](OperationVisitor`2 visitor, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitCore(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.Visit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitArray(IEnumerable`1 operations, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.PointsToAnalysis.PointsToAnalysis.PointsToDataFlowOperationVisitor.DefaultVisit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.PointsToAnalysis.PointsToAnalysis.PointsToDataFlowOperationVisitor.VisitThrow(IThrowOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.BaseThrowExpression.Accept[TArgument,TResult](OperationVisitor`2 visitor, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitCore(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.Visit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitConditional(IConditionalOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.BaseConditionalOperation.Accept[TArgument,TResult](OperationVisitor`2 visitor, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitCore(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.Visit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitArray(IEnumerable`1 operations, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.PointsToAnalysis.PointsToAnalysis.PointsToDataFlowOperationVisitor.DefaultVisit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.OperationVisitor`2.VisitBlock(IBlockOperation operation, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.BaseBlockStatement.Accept[TArgument,TResult](OperationVisitor`2 visitor, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitCore(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.Visit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitArray(IEnumerable`1 operations, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.PointsToAnalysis.PointsToAnalysis.PointsToDataFlowOperationVisitor.DefaultVisit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.OperationVisitor`2.VisitUsing(IUsingOperation operation, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.BaseUsingStatement.Accept[TArgument,TResult](OperationVisitor`2 visitor, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitCore(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.Visit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.Flow(IOperation statement, BasicBlock block, TAnalysisData input)
   at Microsoft.CodeAnalysis.Operations.DataFlow.PointsToAnalysis.PointsToAnalysis.PointsToDataFlowOperationVisitor.Flow(IOperation statement, BasicBlock block, IDictionary`2 input)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowAnalysis`3.Flow(BasicBlock block, TAnalysisData data)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowAnalysis`3.Run(ControlFlowGraph cfg)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowAnalysis`3.GetOrComputeResultCore(ControlFlowGraph cfg)
   at Microsoft.CodeAnalysis.Operations.DataFlow.PointsToAnalysis.PointsToAnalysis.GetOrComputeResult(ControlFlowGraph cfg, ISymbol owningSymbol, DataFlowAnalysisResult`2 nullAnalysisResultOpt, Boolean pessimisticAnalysis)
   at Microsoft.CodeQuality.Analyzers.Exp.DisposeAnalysisHelper.TryGetOrComputeResult(ImmutableArray`1 operationBlocks, IMethodSymbol containingMethod, Boolean trackInstanceFields, ControlFlowGraph& cfg, DataFlowAnalysisResult`2& disposeAnalysisResult, DataFlowAnalysisResult`2& pointsToAnalysisResult, ImmutableDictionary`2& trackedInstanceFieldPointsToMap)
   at Microsoft.CodeQuality.Analyzers.Exp.Reliability.DisposeObjectsBeforeLosingScope.<>c__DisplayClass7_0.<Initialize>b__1(OperationBlockAnalysisContext operationBlockContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__49`2.<ExecuteBlockActions>b__49_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.

```

**Comment by mavasani** [comment]
Does not repro with the latest version of this analyzer package: https://dotnet.myget.org/feed/roslyn-analyzers/package/nuget/Microsoft.CodeAnalysis.FxCopAnalyzers/2.9.0-beta1-63118-01. Note that this analyzer package is based on the compiler CFG API, which is behind a feature flag and needs the project file to have the following property: `<Features>flow-analysis</Features>`
