### ISSUE TITLE
PointsToAnalysis InvalidOperationException in DoNotUseInsecureDeserializerBinaryFormatterWithoutBinderTests.OtherMethodDeserializesWithoutBinderUsingDelegate_Diagnostic()

### ISSUE THREAD

**Issue by dotpaul** [dotnet/roslyn-analyzers#1852]
Run the `DoNotUseInsecureDeserializerBinaryFormatterWithoutBinderTests.OtherMethodDeserializesWithoutBinderUsingDelegate_Diagnostic()` test case, and on my machine, I get:

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Operation is not valid due to the current state of the object.
  Source=Microsoft.NetCore.Analyzers
  StackTrace:
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.DataFlowOperationVisitor`4.GetCachedAbstractValue(IOperation operation) in S:\dp-roslyn-analyzers\src\Utilities\FlowAnalysis\Framework\DataFlow\DataFlowOperationVisitor.cs:line 651
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.PointsToAnalysis.PointsToAnalysis.PointsToDataFlowOperationVisitor.GetPointsToAbstractValue(IOperation operation) in S:\dp-roslyn-analyzers\src\Utilities\FlowAnalysis\Analysis\PointsToAnalysis\PointsToAnalysis.PointsToDataFlowOperationVisitor.cs:line 90
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.DataFlowOperationVisitor`4.GetNullAbstractValue(IOperation operation) in S:\dp-roslyn-analyzers\src\Utilities\FlowAnalysis\Framework\DataFlow\DataFlowOperationVisitor.cs:line 667
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.PointsToAnalysis.PointsToAnalysis.PointsToDataFlowOperationVisitor.GetNullStateBasedOnInstanceOrReferenceValue(IOperation referenceOrInstance, ITypeSymbol operationType, NullAbstractValue defaultValue) in S:\dp-roslyn-analyzers\src\Utilities\FlowAnalysis\Analysis\PointsToAnalysis\PointsToAnalysis.PointsToDataFlowOperationVisitor.cs:line 597
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.PointsToAnalysis.PointsToAnalysis.PointsToDataFlowOperationVisitor.GetValueBasedOnInstanceOrReferenceValue(IOperation referenceOrInstance, IOperation operation, PointsToAbstractValue defaultValue) in S:\dp-roslyn-analyzers\src\Utilities\FlowAnalysis\Analysis\PointsToAnalysis\PointsToAnalysis.PointsToDataFlowOperationVisitor.cs:line 611
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.PointsToAnalysis.PointsToAnalysis.PointsToDataFlowOperationVisitor.VisitInvocationCommon(IOperation operation, IOperation instance) in S:\dp-roslyn-analyzers\src\Utilities\FlowAnalysis\Analysis\PointsToAnalysis\PointsToAnalysis.PointsToDataFlowOperationVisitor.cs:line 544
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.PointsToAnalysis.PointsToAnalysis.PointsToDataFlowOperationVisitor.VisitInvocation_NonLambdaOrDelegateOrLocalFunction(IMethodSymbol method, IOperation visitedInstance, ImmutableArray`1 visitedArguments, Boolean invokedAsDelegate, IOperation originalOperation, PointsToAbstractValue defaultValue) in S:\dp-roslyn-analyzers\src\Utilities\FlowAnalysis\Analysis\PointsToAnalysis\PointsToAnalysis.PointsToDataFlowOperationVisitor.cs:line 561
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.DataFlowOperationVisitor`4.<>c__DisplayClass172_2.<VisitInvocation_LambdaOrDelegateOrLocalFunction>b__6() in S:\dp-roslyn-analyzers\src\Utilities\FlowAnalysis\Framework\DataFlow\DataFlowOperationVisitor.cs:line 2181
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.DataFlowOperationVisitor`4.<>c__DisplayClass172_0.<VisitInvocation_LambdaOrDelegateOrLocalFunction>g__AnalyzePossibleTargetInvocation|5(Func`1 computeValueForInvocation, TAnalysisData inputAnalysisData, TAnalysisData mergedAnalysisData, Boolean& first) in S:\dp-roslyn-analyzers\src\Utilities\FlowAnalysis\Framework\DataFlow\DataFlowOperationVisitor.cs:line 2209
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.DataFlowOperationVisitor`4.<>c__DisplayClass172_0.<VisitInvocation_LambdaOrDelegateOrLocalFunction>g__AnalyzePossibleTargetInvocations|4() in S:\dp-roslyn-analyzers\src\Utilities\FlowAnalysis\Framework\DataFlow\DataFlowOperationVisitor.cs:line 2180
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.DataFlowOperationVisitor`4.VisitInvocation_LambdaOrDelegateOrLocalFunction(IInvocationOperation operation, Object argument, HashSet`1& resolvedMethodTargetsOpt) in S:\dp-roslyn-analyzers\src\Utilities\FlowAnalysis\Framework\DataFlow\DataFlowOperationVisitor.cs:line 2098
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.DataFlowOperationVisitor`4.VisitInvocation(IInvocationOperation operation, Object argument) in S:\dp-roslyn-analyzers\src\Utilities\FlowAnalysis\Framework\DataFlow\DataFlowOperationVisitor.cs:line 2007
   at Microsoft.CodeAnalysis.Operations.BaseInvocationExpression.Accept[TArgument,TResult](OperationVisitor`2 visitor, TArgument argument)
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.DataFlowOperationVisitor`4.VisitCore(IOperation operation, Object argument) in S:\dp-roslyn-analyzers\src\Utilities\FlowAnalysis\Framework\DataFlow\DataFlowOperationVisitor.cs:line 1688
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.DataFlowOperationVisitor`4.Visit(IOperation operation, Object argument) in S:\dp-roslyn-analyzers\src\Utilities\FlowAnalysis\Framework\DataFlow\DataFlowOperationVisitor.cs:line 1647
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.DataFlowOperationVisitor`4.FlowBranch(BasicBlock fromBlock, BranchWithInfo branch, TAnalysisData input) in S:\dp-roslyn-analyzers\src\Utilities\FlowAnalysis\Framework\DataFlow\DataFlowOperationVisitor.cs:line 463
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.DataFlowAnalysis`5.Run(TAnalysisContext analysisContext) in S:\dp-roslyn-analyzers\src\Utilities\FlowAnalysis\Framework\DataFlow\DataFlowAnalysis.cs:line 189
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.DataFlowAnalysis`5.<>c__DisplayClass12_0.<GetOrComputeResultCore>b__0(DataFlowOperationVisitor`4 _) in S:\dp-roslyn-analyzers\src\Utilities\FlowAnalysis\Framework\DataFlow\DataFlowAnalysis.cs:line 50
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.DataFlowAnalysis`5.GetOrComputeResultCore(TAnalysisContext analysisContext, Boolean cacheResult) in S:\dp-roslyn-analyzers\src\Utilities\FlowAnalysis\Framework\DataFlow\DataFlowAnalysis.cs:line 50
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.PointsToAnalysis.PointsToAnalysis.GetOrComputeResultForAnalysisContext(PointsToAnalysisContext analysisContext) in S:\dp-roslyn-analyzers\src\Utilities\FlowAnalysis\Analysis\PointsToAnalysis\PointsToAnalysis.cs:line 57
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.DataFlowOperationVisitor`4.PerformInterproceduralAnalysis(Func`1 getCfg, IMethodSymbol invokedMethod, IOperation instanceReceiver, ImmutableArray`1 arguments, IOperation originalOperation, TAbstractAnalysisValue defaultValue, Boolean isLambdaOrLocalFunction) in S:\dp-roslyn-analyzers\src\Utilities\FlowAnalysis\Framework\DataFlow\DataFlowOperationVisitor.cs:line 1466
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.DataFlowOperationVisitor`4.VisitInvocation_NonLambdaOrDelegateOrLocalFunction(IMethodSymbol method, IOperation visitedInstance, ImmutableArray`1 visitedArguments, Boolean invokedAsDelegate, IOperation originalOperation, TAbstractAnalysisValue defaultValue) in S:\dp-roslyn-analyzers\src\Utilities\FlowAnalysis\Framework\DataFlow\DataFlowOperationVisitor.cs:line 2249
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.PointsToAnalysis.PointsToAnalysis.PointsToDataFlowOperationVisitor.VisitInvocation_NonLambdaOrDelegateOrLocalFunction(IMethodSymbol method, IOperation visitedInstance, ImmutableArray`1 visitedArguments, Boolean invokedAsDelegate, IOperation originalOperation, PointsToAbstractValue defaultValue) in S:\dp-roslyn-analyzers\src\Utilities\FlowAnalysis\Analysis\PointsToAnalysis\PointsToAnalysis.PointsToDataFlowOperationVisitor.cs:line 560
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.DataFlowOperationVisitor`4.VisitInvocation_NonLambdaOrDelegateOrLocalFunction(IInvocationOperation operation, Object argument) in S:\dp-roslyn-analyzers\src\Utilities\FlowAnalysis\Framework\DataFlow\DataFlowOperationVisitor.cs:line 2050
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.DataFlowOperationVisitor`4.VisitInvocation(IInvocationOperation operation, Object argument) in S:\dp-roslyn-analyzers\src\Utilities\FlowAnalysis\Framework\DataFlow\DataFlowOperationVisitor.cs:line 2020
   at Microsoft.CodeAnalysis.Operations.BaseInvocationExpression.Accept[TArgument,TResult](OperationVisitor`2 visitor, TArgument argument)
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.DataFlowOperationVisitor`4.VisitCore(IOperation operation, Object argument) in S:\dp-roslyn-analyzers\src\Utilities\FlowAnalysis\Framework\DataFlow\DataFlowOperationVisitor.cs:line 1688
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.DataFlowOperationVisitor`4.Visit(IOperation operation, Object argument) in S:\dp-roslyn-analyzers\src\Utilities\FlowAnalysis\Framework\DataFlow\DataFlowOperationVisitor.cs:line 1647
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.DataFlowOperationVisitor`4.FlowBranch(BasicBlock fromBlock, BranchWithInfo branch, TAnalysisData input) in S:\dp-roslyn-analyzers\src\Utilities\FlowAnalysis\Framework\DataFlow\DataFlowOperationVisitor.cs:line 463
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.DataFlowAnalysis`5.Run(TAnalysisContext analysisContext) in S:\dp-roslyn-analyzers\src\Utilities\FlowAnalysis\Framework\DataFlow\DataFlowAnalysis.cs:line 189
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.DataFlowAnalysis`5.<>c__DisplayClass12_0.<GetOrComputeResultCore>b__0(DataFlowOperationVisitor`4 _) in S:\dp-roslyn-analyzers\src\Utilities\FlowAnalysis\Framework\DataFlow\DataFlowAnalysis.cs:line 50
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.DataFlowAnalysis`5.GetOrComputeResultCore(TAnalysisContext analysisContext, Boolean cacheResult) in S:\dp-roslyn-analyzers\src\Utilities\FlowAnalysis\Framework\DataFlow\DataFlowAnalysis.cs:line 50
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.PointsToAnalysis.PointsToAnalysis.GetOrComputeResultForAnalysisContext(PointsToAnalysisContext analysisContext) in S:\dp-roslyn-analyzers\src\Utilities\FlowAnalysis\Analysis\PointsToAnalysis\PointsToAnalysis.cs:line 57
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.PointsToAnalysis.PointsToAnalysis.GetOrComputeResult(ControlFlowGraph cfg, ISymbol owningSymbol, WellKnownTypeProvider wellKnownTypeProvider, DataFlowAnalysisResult`2& copyAnalysisResultOpt, InterproceduralAnalysisKind interproceduralAnalysisKind, Boolean pessimisticAnalysis, Boolean performCopyAnalysis) in S:\dp-roslyn-analyzers\src\Utilities\FlowAnalysis\Analysis\PointsToAnalysis\PointsToAnalysis.cs:line 48
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.PointsToAnalysis.PointsToAnalysis.GetOrComputeResult(ControlFlowGraph cfg, ISymbol owningSymbol, WellKnownTypeProvider wellKnownTypeProvider, InterproceduralAnalysisKind interproceduralAnalysisKind, Boolean pessimisticAnalysis, Boolean performCopyAnalysis) in S:\dp-roslyn-analyzers\src\Utilities\FlowAnalysis\Analysis\PointsToAnalysis\PointsToAnalysis.cs:line 29
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.CopyAnalysis.CopyAnalysis.GetOrComputeResult(ControlFlowGraph cfg, ISymbol owningSymbol, WellKnownTypeProvider wellKnownTypeProvider, InterproceduralAnalysisKind interproceduralAnalysisKind, Boolean pessimisticAnalysis, Boolean performPointsToAnalysis) in S:\dp-roslyn-analyzers\src\Utilities\FlowAnalysis\Analysis\CopyAnalysis\CopyAnalysis.cs:line 32
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.PointsToAnalysis.PointsToAnalysis.GetOrComputeResult(ControlFlowGraph cfg, ISymbol owningSymbol, WellKnownTypeProvider wellKnownTypeProvider, DataFlowAnalysisResult`2& copyAnalysisResultOpt, InterproceduralAnalysisKind interproceduralAnalysisKind, Boolean pessimisticAnalysis, Boolean performCopyAnalysis) in S:\dp-roslyn-analyzers\src\Utilities\FlowAnalysis\Analysis\PointsToAnalysis\PointsToAnalysis.cs:line 42
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.PointsToAnalysis.PointsToAnalysis.GetOrComputeResult(ControlFlowGraph cfg, ISymbol owningSymbol, WellKnownTypeProvider wellKnownTypeProvider, InterproceduralAnalysisKind interproceduralAnalysisKind, Boolean pessimisticAnalysis, Boolean performCopyAnalysis) in S:\dp-roslyn-analyzers\src\Utilities\FlowAnalysis\Analysis\PointsToAnalysis\PointsToAnalysis.cs:line 29
   at Analyzer.Utilities.FlowAnalysis.Analysis.PropertySetAnalysis.PropertySetAnalysis.GetOrComputeHazardousParameterUsages(ControlFlowGraph cfg, Compilation compilation, ISymbol owningSymbol, String typeToTrackMetadataName, Boolean isNewInstanceFlagged, String propertyToSetFlag, Boolean isNullPropertyFlagged, ImmutableHashSet`1 methodNamesToCheckForFlaggedUsage, InterproceduralAnalysisKind interproceduralAnalysisKind, Boolean pessimisticAnalysis) in S:\dp-roslyn-analyzers\src\Utilities\FlowAnalysis\Analysis\PropertySetAnalysis\PropertySetAnalysis.cs:line 45
   at Microsoft.NetCore.Analyzers.Security.DoNotUseInsecureDeserializerWithoutBinderBase.<>c__DisplayClass12_2.<Initialize>b__4(OperationBlockAnalysisContext operationBlockAnalysisContext) in S:\dp-roslyn-analyzers\src\Microsoft.NetCore.Analyzers\Core\Security\DoNotUseInsecureDeserializerWithoutBinderBase.cs:line 135
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__49`2.<ExecuteBlockActions>b__49_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
```

**Comment by dotpaul** [comment]
I'll try to provide a more isolated repro.  If you want to try it with the latest PR, you'll have to change PropertySetAnalysis to use interprocedural again.

**Comment by mavasani** [comment]
Great thanks

**Comment by dotpaul** [comment]
Oh, just putting that same test sample code in `ValidateArgumentsOfPublicMethodsTests` repros the issue.  I have a branch here with that: https://github.com/dotpaul/roslyn-analyzers/tree/features/dataflow_issue1852test

Or you can just copy and paste this test case:
```csharp
        [Fact]
        public void Issue1852()
        {
            VerifyCSharp(@"
using System;
using System.IO;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Formatters.Binary;
using System.Runtime.Remoting.Messaging;

namespace Blah
{
    public class Program
    {
        delegate object Des(Stream s);

        public object Deserialize(byte[] bytes)
        {
            BinaryFormatter formatter = new BinaryFormatter();
            return DoDeserialization(formatter.Deserialize, new MemoryStream(bytes));
        }

        private object DoDeserialization(Des des, Stream stream)
        {
            return des(stream);
        }
    }
}");
        }
```

**Comment by sharwell** [comment]
Reopening as there is a test that is skipped for this issue, and if unskipped it fails.

https://github.com/dotnet/roslyn-analyzers/blob/9fa03861d0b8979b0536cae0b9d0f7d60336eb09/src/Microsoft.NetCore.Analyzers/UnitTests/Security/DoNotUseInsecureDeserializerBinaryFormatterWithoutBinderTests.cs#L836-L837

**Comment by mavasani** [comment]
Test is no longer skipped: https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.NetCore.Analyzers/UnitTests/Security/DoNotUseInsecureDeserializerBinaryFormatterWithoutBinderTests.cs#L1087
