### ISSUE TITLE
Auto Add Public API Interface to PublicAPI.txt fails in Visual Studios Dev16.

### ISSUE THREAD

**Issue by EricJosephGreen** [dotnet/roslyn-analyzers#1867]
#### Analyzer package

Roslyn.Diagnostics.Analyzers

#### Analyzer

RS0016: DeclarePublicAPIAnalyzer

#### Repro steps

1. Get a preview version of Visual Studio 2019.
1. Try to add a new interface to a dll in Visual Studios that is apart of a public API
1. There should be a green squiggle under the interface name and it's method saying, "[interface name] not apart of the declared public API".
1. Click Ctrl+. to use the auto correct feature, and try to add the interface to the declared public API. 

#### Expected behavior

Interface is added

#### Actual behavior

Error is thrown with the output that looks like this:
![image](https://user-images.githubusercontent.com/44481820/47530357-3788b900-d85f-11e8-9bdf-4547998c5096.png)

The Stack Trace showed this:

System.AggregateException : One or more errors occurred. ---> Unable to check out the files from source control.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass18_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
---> (Inner Exception #0) System.Exception : Unable to check out the files from source control.
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.EnsureEditableDocuments(IEnumerable`1 documents)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyTextDocumentChange(DocumentId documentId,SourceText newText)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyAdditionalDocumentTextChanged(DocumentId documentId,SourceText newText)
   at Microsoft.CodeAnalysis.Workspace.ApplyProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.TryApply(Workspace workspace,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.Apply(Workspace workspace,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ApplyAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)<---

**Comment by jasonmalinowski** [comment]
Fixed by dotnet/roslyn#30675.
