### ISSUE TITLE
'Microsoft.CodeQuality.Analyzers.Exp.Maintainability.AvoidDeadConditionalCode' threw an exception of type 'System.Collections.Generic.KeyNotFoundException' with message 'The given key was not present in the dictionary.'

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn-analyzers#1917]
```ini
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Error	AD0001	Analyzer 'Microsoft.CodeQuality.Analyzers.Exp.Maintainability.AvoidDeadConditionalCode' threw an exception of type 'System.Collections.Generic.KeyNotFoundException' with message 'The given key was not present in the dictionary.'.	Microsoft.VisualStudio.Editors		1	Active	Analyzer 'Microsoft.CodeQuality.Analyzers.Exp.Maintainability.AvoidDeadConditionalCode' threw the following exception:
'Exception occurred with following context:
Compilation: Microsoft.VisualStudio.Editors
ISymbol: AddOutsideFileToProject (Method)

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitTry(ITryOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.BaseTryStatement.Accept[TArgument,TResult](OperationVisitor`2 visitor, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitCore(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.Visit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.Flow(IOperation statement, BasicBlock block, TAnalysisData input)
   at Microsoft.CodeAnalysis.Operations.DataFlow.PointsToAnalysis.PointsToAnalysis.PointsToDataFlowOperationVisitor.Flow(IOperation statement, BasicBlock block, IDictionary`2 input)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowAnalysis`3.Flow(DataFlowOperationVisitor`2 operationVisitor, BasicBlock block, TAnalysisData data)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowAnalysis`3.Run(ControlFlowGraph cfg, DataFlowAnalysisResult`2 seedResultOpt)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowAnalysis`3.<>c__DisplayClass8_0.<GetOrComputeResultCore>b__0(DataFlowOperationVisitor`2 _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowAnalysis`3.GetOrComputeResultCore(ControlFlowGraph cfg, Boolean cacheResult, DataFlowAnalysisResult`2 seedResultOpt)
   at Microsoft.CodeAnalysis.Operations.DataFlow.PointsToAnalysis.PointsToAnalysis.GetOrComputeResult(ControlFlowGraph cfg, ISymbol owningSymbol, WellKnownTypeProvider wellKnownTypeProvider, DataFlowAnalysisResult`2 pointsToAnalysisResultOpt, DataFlowAnalysisResult`2 copyAnalysisResultOpt, Boolean pessimisticAnalysis)
   at Microsoft.CodeQuality.Analyzers.Exp.Maintainability.AvoidDeadConditionalCode.<>c.<Initialize>b__8_1(OperationBlockStartAnalysisContext operationBlockStartContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__54`6.<ExecuteBlockActionsCore>b__54_2(ValueTuple`5 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.

```

**Comment by mavasani** [comment]
I believe this bug is only repro-able in the now deprecated `Microsoft.CodeQuality.Analyzers.Exp.nupkg`. The latest implementation in master for top of the stack method `DataFlowOperationVisitor`2.VisitTry` is here: https://github.com/dotnet/roslyn-analyzers/blob/master/src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs#L3229-L3232, which throws an unconditional `InvalidProgramException` as the latest CFG APIs guarantee that ITryOperation is lowered in the CFG.

I am going to close this bug as no-repro and request you to remove the NuGet package reference to `Microsoft.CodeQuality.Analyzers.Exp.nupkg`
