### ISSUE TITLE
'Microsoft.CodeQuality.Analyzers.Exp.Globalization.DoNotPassLiteralsAsLocalizedParameters' threw an exception of type 'System.Collections.Generic.KeyNotFoundException' with message 'The given key was not present in the dictionary.'

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn-analyzers#1918]
```ini
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Error	AD0001	Analyzer 'Microsoft.CodeQuality.Analyzers.Exp.Globalization.DoNotPassLiteralsAsLocalizedParameters' threw an exception of type 'System.Collections.Generic.KeyNotFoundException' with message 'The given key was not present in the dictionary.'.	Microsoft.VisualStudio.Editors		1	Active	Analyzer 'Microsoft.CodeQuality.Analyzers.Exp.Globalization.DoNotPassLiteralsAsLocalizedParameters' threw the following exception:
'Exception occurred with following context:
Compilation: Microsoft.VisualStudio.Editors
IOperation: Argument
SyntaxTree: C:\source\project-system\src\Microsoft.VisualStudio.Editors\ResourceEditor\ResourcesFolderService.vb
SyntaxNode: My.Resources.Microsoft_VisualStudio_Editors_Designer ... [SimpleArgumentSyntax]@[27549..27712) (464,60)-(464,223)

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitTry(ITryOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.BaseTryStatement.Accept[TArgument,TResult](OperationVisitor`2 visitor, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitCore(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.Visit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.Flow(IOperation statement, BasicBlock block, TAnalysisData input)
   at Microsoft.CodeAnalysis.Operations.DataFlow.PointsToAnalysis.PointsToAnalysis.PointsToDataFlowOperationVisitor.Flow(IOperation statement, BasicBlock block, IDictionary`2 input)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowAnalysis`3.Flow(DataFlowOperationVisitor`2 operationVisitor, BasicBlock block, TAnalysisData data)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowAnalysis`3.Run(ControlFlowGraph cfg, DataFlowAnalysisResult`2 seedResultOpt)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowAnalysis`3.<>c__DisplayClass8_0.<GetOrComputeResultCore>b__0(DataFlowOperationVisitor`2 _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowAnalysis`3.GetOrComputeResultCore(ControlFlowGraph cfg, Boolean cacheResult, DataFlowAnalysisResult`2 seedResultOpt)
   at Microsoft.CodeAnalysis.Operations.DataFlow.PointsToAnalysis.PointsToAnalysis.GetOrComputeResult(ControlFlowGraph cfg, ISymbol owningSymbol, WellKnownTypeProvider wellKnownTypeProvider, DataFlowAnalysisResult`2 pointsToAnalysisResultOpt, DataFlowAnalysisResult`2 copyAnalysisResultOpt, Boolean pessimisticAnalysis)
   at Microsoft.CodeQuality.Analyzers.Exp.Globalization.DoNotPassLiteralsAsLocalizedParameters.<>c__DisplayClass7_1.<Initialize>g__ComputeStringContentAnalysisResult|5()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.CodeQuality.Analyzers.Exp.Globalization.DoNotPassLiteralsAsLocalizedParameters.<>c__DisplayClass7_1.<Initialize>g__AnalyzeArgument|4(IParameterSymbol parameter, IPropertySymbol containingPropertySymbolOpt, IOperation operation, Action`1 reportDiagnostic)
   at Microsoft.CodeQuality.Analyzers.Exp.Globalization.DoNotPassLiteralsAsLocalizedParameters.<>c__DisplayClass7_1.<Initialize>b__2(OperationAnalysisContext operationContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteOperationAction>b__51_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.

```

**Comment by mavasani** [comment]
Tagging @tmeschter as he also saw this locally.

I believe this bug is only repro-able in the now deprecated `Microsoft.CodeQuality.Analyzers.Exp.nupkg`. The latest implementation in master for top of the stack method `DataFlowOperationVisitor`2.VisitTry` is here: https://github.com/dotnet/roslyn-analyzers/blob/master/src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs#L3229-L3232, which throws an unconditional `InvalidProgramException` as the latest CFG APIs guarantee that ITryOperation is lowered in the CFG.

I am going to close this bug as no-repro and request you to remove the NuGet package reference to `Microsoft.CodeQuality.Analyzers.Exp.nupkg`

**Comment by tmeschter** [comment]
@mavasani After removing that package I no longer get _any_ of the AD0001 errors I was previously seeing.

Have all the analyzers in this package been rolled into Microsoft.CodeQuality.Analyzers?

**Comment by mavasani** [comment]
> Have all the analyzers in this package been rolled into Microsoft.CodeQuality.Analyzers?

All of them have been rolled into one of the 3 packages that ship in FxCop analyzers: https://github.com/dotnet/roslyn-analyzers#the-following-are-subpackages-or-nuget-dependencies-that-are-automatically-installed-when-you-install-the-microsoftcodeanalysisfxcopanalyzers-package
