### ISSUE TITLE
'Microsoft.CodeQuality.Analyzers.Exp.Globalization.DoNotPassLiteralsAsLocalizedParameters' threw an exception of type 'System.NullReferenceException'

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn-analyzers#1919]
```ini
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Error	AD0001	Analyzer 'Microsoft.CodeQuality.Analyzers.Exp.Globalization.DoNotPassLiteralsAsLocalizedParameters' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS		1	Active	Analyzer 'Microsoft.CodeQuality.Analyzers.Exp.Globalization.DoNotPassLiteralsAsLocalizedParameters' threw the following exception:
'Exception occurred with following context:
Compilation: Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS
IOperation: Argument
SyntaxTree: C:\source\project-system\src\Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS\ProjectSystem\VS\Automation\VisualBasicVSImports.cs
SyntaxNode: importNamespace [ArgumentSyntax]@[6375..6390) (148,32)-(148,47)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeQuality.Analyzers.Exp.Globalization.DoNotPassLiteralsAsLocalizedParameters.ShouldBeLocalized(IParameterSymbol parameterSymbol, IPropertySymbol containingPropertySymbolOpt, INamedTypeSymbol localizableStateAttributeSymbol, INamedTypeSymbol conditionalAttributeSymbol, INamedTypeSymbol systemConsoleSymbol, ImmutableHashSet`1 typesToIgnore)
   at Microsoft.CodeQuality.Analyzers.Exp.Globalization.DoNotPassLiteralsAsLocalizedParameters.<>c__DisplayClass7_1.<Initialize>g__AnalyzeArgument|4(IParameterSymbol parameter, IPropertySymbol containingPropertySymbolOpt, IOperation operation, Action`1 reportDiagnostic)
   at Microsoft.CodeQuality.Analyzers.Exp.Globalization.DoNotPassLiteralsAsLocalizedParameters.<>c__DisplayClass7_1.<Initialize>b__2(OperationAnalysisContext operationContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteOperationAction>b__51_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.

```

**Comment by samcragg** [comment]
I'n getting this error too with Microsoft.CodeAnalysis.FxCopAnalyzers (version 2.9.3) against a .NET Core 2.1 console app with Visual Studio 2019 (16.1.3) - I was able to narrow it down to the following usage (note the generic parameter and the virtual method calling the base class - this seemed to be the combination that triggered it).

Here's the stack trace reported by Visual Studio:

```
'Microsoft.NetCore.Analyzers.Runtime.DoNotPassLiteralsAsLocalizedParameters' threw the following exception:
'Exception occurred with following context:
Compilation: AnalyzerError
IOperation: Argument
SyntaxTree: C:\Code\AnalyzerError\Program.cs
SyntaxNode: "number" [ArgumentSyntax]@[292..300) (10,59)-(10,67)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.NetCore.Analyzers.Runtime.DoNotPassLiteralsAsLocalizedParameters.ShouldBeLocalized(IParameterSymbol parameterSymbol, IPropertySymbol containingPropertySymbolOpt, INamedTypeSymbol localizableStateAttributeSymbol, INamedTypeSymbol conditionalAttributeSymbol, INamedTypeSymbol systemConsoleSymbol, ImmutableHashSet`1 typesToIgnore)
   at Microsoft.NetCore.Analyzers.Runtime.DoNotPassLiteralsAsLocalizedParameters.<>c__DisplayClass7_1.<Initialize>g__AnalyzeArgument|4(IParameterSymbol parameter, IPropertySymbol containingPropertySymbolOpt, IOperation operation, Action`1 reportDiagnostic)
   at Microsoft.NetCore.Analyzers.Runtime.DoNotPassLiteralsAsLocalizedParameters.<>c__DisplayClass7_1.<Initialize>b__2(OperationAnalysisContext operationContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteOperationAction>b__51_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.
```

The minimal code that I got to trigger the above was:

```C#
internal static class Program
{
    public static void Main()
    {
        new DerivedClass().Generic<decimal>("number");
    }

    private class BaseClass
    {
        public virtual T Generic<T>(string type) => default;
    }

    private class DerivedClass : BaseClass
    {
        public override T Generic<T>(string type) => base.Generic<T>(type);
    }
}
```
