### ISSUE TITLE
NRE in DisposeDataFlowAnalysis

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#2657]
```
Severity	Code	Description	Project	File	Line	Source	Suppression State	Detail Description
Error	AD0001	Analyzer 'Microsoft.CodeQuality.Analyzers.Exp.Reliability.DisposeObjectsBeforeLosingScope' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	Microsoft.VisualStudio.Editors		1	IntelliSense	Active	Analyzer 'Microsoft.CodeQuality.Analyzers.Exp.Reliability.DisposeObjectsBeforeLosingScope' threw the following exception:
'Exception occurred with following context:
Compilation: Microsoft.VisualStudio.Editors
ISymbol: GetInstalledFxCopAnalyzersVersion (Method)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitArrayInitializer(IArrayInitializerOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.PointsToAnalysis.PointsToAnalysis.PointsToDataFlowOperationVisitor.VisitArrayInitializer(IArrayInitializerOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.BaseArrayInitializerOperation.Accept[TArgument,TResult](OperationVisitor`2 visitor, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitCore(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.Visit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitArray(IEnumerable`1 operations, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.PointsToAnalysis.PointsToAnalysis.PointsToDataFlowOperationVisitor.DefaultVisit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitCore(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.Visit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitArray(IEnumerable`1 operations, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.PointsToAnalysis.PointsToAnalysis.PointsToDataFlowOperationVisitor.DefaultVisit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.OperationVisitor`2.VisitInvalid(IInvalidOperation operation, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.BaseInvalidOperation.Accept[TArgument,TResult](OperationVisitor`2 visitor, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitCore(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.Visit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitBinaryOperator_NonConditional(IBinaryOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.PointsToAnalysis.PointsToAnalysis.PointsToDataFlowOperationVisitor.VisitBinaryOperator_NonConditional(IBinaryOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitBinaryOperator(IBinaryOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.BaseBinaryOperation.Accept[TArgument,TResult](OperationVisitor`2 visitor, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitCore(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.Visit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitArray(IEnumerable`1 operations, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.PointsToAnalysis.PointsToAnalysis.PointsToDataFlowOperationVisitor.DefaultVisit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.OperationVisitor`2.VisitInvalid(IInvalidOperation operation, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.BaseInvalidOperation.Accept[TArgument,TResult](OperationVisitor`2 visitor, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitCore(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.Visit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitArray(IEnumerable`1 operations, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.PointsToAnalysis.PointsToAnalysis.PointsToDataFlowOperationVisitor.DefaultVisit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.OperationVisitor`2.VisitExpressionStatement(IExpressionStatementOperation operation, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.BaseExpressionStatementOperation.Accept[TArgument,TResult](OperationVisitor`2 visitor, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitCore(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.Visit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitArray(IEnumerable`1 operations, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.PointsToAnalysis.PointsToAnalysis.PointsToDataFlowOperationVisitor.DefaultVisit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.OperationVisitor`2.VisitBlock(IBlockOperation operation, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.BaseBlockOperation.Accept[TArgument,TResult](OperationVisitor`2 visitor, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitCore(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.Visit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitConditional(IConditionalOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.BaseConditionalOperation.Accept[TArgument,TResult](OperationVisitor`2 visitor, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitCore(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.Visit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.Flow(IOperation statement, BasicBlock block, TAnalysisData input)
   at Microsoft.CodeAnalysis.Operations.DataFlow.PointsToAnalysis.PointsToAnalysis.PointsToDataFlowOperationVisitor.Flow(IOperation statement, BasicBlock block, IDictionary`2 input)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowAnalysis`3.Flow(DataFlowOperationVisitor`2 operationVisitor, BasicBlock block, TAnalysisData data)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowAnalysis`3.Run(ControlFlowGraph cfg, DataFlowAnalysisResult`2 seedResultOpt)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowAnalysis`3.<>c__DisplayClass8_0.<GetOrComputeResultCore>b__0(DataFlowOperationVisitor`2 _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowAnalysis`3.GetOrComputeResultCore(ControlFlowGraph cfg, Boolean cacheResult, DataFlowAnalysisResult`2 seedResultOpt)
   at Microsoft.CodeAnalysis.Operations.DataFlow.PointsToAnalysis.PointsToAnalysis.GetOrComputeResult(ControlFlowGraph cfg, ISymbol owningSymbol, WellKnownTypeProvider wellKnownTypeProvider, DataFlowAnalysisResult`2 pointsToAnalysisResultOpt, DataFlowAnalysisResult`2 copyAnalysisResultOpt, Boolean pessimisticAnalysis)
   at Microsoft.CodeQuality.Analyzers.Exp.DisposeAnalysisHelper.TryGetOrComputeResult(ImmutableArray`1 operationBlocks, IMethodSymbol containingMethod, Boolean trackInstanceFields, DataFlowAnalysisResult`2& disposeAnalysisResult, DataFlowAnalysisResult`2& pointsToAnalysisResult, ImmutableDictionary`2& trackedInstanceFieldPointsToMap)
   at Microsoft.CodeQuality.Analyzers.Exp.Reliability.DisposeObjectsBeforeLosingScope.<>c__DisplayClass7_0.<Initialize>b__1(OperationBlockAnalysisContext operationBlockContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__55`2.<ExecuteBlockActions>b__55_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.
```

**Comment by mavasani** [comment]
Duplicate of https://github.com/dotnet/roslyn-analyzers/pull/2478
