### ISSUE TITLE
DoNotCallDangerousMethodsInDeserialization: The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-analyzers#2683]
#### Analyzer package

Microsoft.NetCore.Analyzers

#### Package Version

v2.9.3

#### Diagnostic ID

CA5360

#### Repro steps
```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Error	AD0001	Analyzer 'Microsoft.NetCore.Analyzers.Security.DoNotCallDangerousMethodsInDeserialization' threw an exception of type 'System.Collections.Generic.KeyNotFoundException' with message 'The given key was not present in the dictionary.'.	Microsoft.VisualStudio.Editors		1	Active	Analyzer 'Microsoft.NetCore.Analyzers.Security.DoNotCallDangerousMethodsInDeserialization' threw the following exception:
'Exception occurred with following context:
Compilation: Microsoft.VisualStudio.Editors

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at Microsoft.NetCore.Analyzers.Security.DoNotCallDangerousMethodsInDeserialization.<>c__DisplayClass8_0.<Initialize>g__FindCalledDangerousMethod|3(IMethodSymbol methodSymbol, HashSet`1 visited, Dictionary`2 results)
   at Microsoft.NetCore.Analyzers.Security.DoNotCallDangerousMethodsInDeserialization.<>c__DisplayClass8_0.<Initialize>g__FindCalledDangerousMethod|3(IMethodSymbol methodSymbol, HashSet`1 visited, Dictionary`2 results)
   at Microsoft.NetCore.Analyzers.Security.DoNotCallDangerousMethodsInDeserialization.<>c__DisplayClass8_0.<Initialize>g__FindCalledDangerousMethod|3(IMethodSymbol methodSymbol, HashSet`1 visited, Dictionary`2 results)
   at Microsoft.NetCore.Analyzers.Security.DoNotCallDangerousMethodsInDeserialization.<>c__DisplayClass8_0.<Initialize>g__FindCalledDangerousMethod|3(IMethodSymbol methodSymbol, HashSet`1 visited, Dictionary`2 results)
   at Microsoft.NetCore.Analyzers.Security.DoNotCallDangerousMethodsInDeserialization.<>c__DisplayClass8_0.<Initialize>g__FindCalledDangerousMethod|3(IMethodSymbol methodSymbol, HashSet`1 visited, Dictionary`2 results)
   at Microsoft.NetCore.Analyzers.Security.DoNotCallDangerousMethodsInDeserialization.<>c__DisplayClass8_0.<Initialize>g__FindCalledDangerousMethod|3(IMethodSymbol methodSymbol, HashSet`1 visited, Dictionary`2 results)
   at Microsoft.NetCore.Analyzers.Security.DoNotCallDangerousMethodsInDeserialization.<>c__DisplayClass8_0.<Initialize>g__FindCalledDangerousMethod|3(IMethodSymbol methodSymbol, HashSet`1 visited, Dictionary`2 results)
   at Microsoft.NetCore.Analyzers.Security.DoNotCallDangerousMethodsInDeserialization.<>c__DisplayClass8_0.<Initialize>b__2(CompilationAnalysisContext compilationAnalysisContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteCompilationActionsCore>b__41_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.

```

**Comment by mavasani** [comment]
I believe this was fixed with https://github.com/dotnet/roslyn-analyzers/pull/2594 and should be part of 2.9.4-beta1.final.

Tagging @LLLXXXCCC
