### ISSUE TITLE
'Microsoft.NetCore.Analyzers.Data.ReviewSqlQueriesForSecurityVulnerabilities' threw an exception of type 'System.NullReferenceException' 

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn-analyzers#2694]
Using Visual Studio 16.3.0 Preview 1.0.

The call stack is different from https://github.com/dotnet/roslyn-analyzers/issues/2502.

The version of the file that triggered it is https://github.com/dotnet/roslyn/blob/dfc664f7a9eba2d9c6d09a4e3bb8910661d6086f/src/EditorFeatures/CSharpTest/EditAndContinue/TopLevelEditingTests.cs.

```
Severity	Code	Description	File	Project	Line	Suppression State	Detail Description
Error	AD0001	Analyzer 'Microsoft.NetCore.Analyzers.Data.ReviewSqlQueriesForSecurityVulnerabilities' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.		Microsoft.CodeAnalysis.CSharp.EditorFeatures.UnitTests	1	Active	Analyzer 'Microsoft.NetCore.Analyzers.Data.ReviewSqlQueriesForSecurityVulnerabilities' threw the following exception:
'Exception occurred with following context:
Compilation: Microsoft.CodeAnalysis.CSharp.EditorFeatures.UnitTests
IOperation: PropertyReference
SyntaxTree: C:\Users\Joseph\Source\Repos\roslyn\src\EditorFeatures\CSharpTest\EditAndContinue\TopLevelEditingTests.cs
SyntaxNode: c.GetMember<NamedTypeSymbol>("C" ... [MemberAccessExpressionSyntax]@[134367..134419) (4619,63)-(4619,115)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.Symbols.MemberSignatureComparer.HaveSameReturnTypes(Symbol member1, TypeMap typeMap1, Symbol member2, TypeMap typeMap2, TypeCompareKind typeComparison)
   at Microsoft.CodeAnalysis.CSharp.Symbols.MemberSignatureComparer.Equals(Symbol member1, Symbol member2)
   at Microsoft.CodeAnalysis.CSharp.Symbols.Retargeting.RetargetingModuleSymbol.RetargetingSymbolTranslator.FindPropertyInRetargetedType(PropertySymbol property, NamedTypeSymbol retargetedType, IEqualityComparer`1 retargetedPropertyComparer)
   at Microsoft.CodeAnalysis.CSharp.Symbols.Retargeting.RetargetingModuleSymbol.RetargetingSymbolTranslator.Retarget(PropertySymbol property, IEqualityComparer`1 retargetedPropertyComparer)
   at Microsoft.CodeAnalysis.CSharp.Symbols.Retargeting.RetargetingPropertySymbol.RetargetExplicitInterfaceImplementations()
   at Microsoft.CodeAnalysis.CSharp.Symbols.Retargeting.RetargetingPropertySymbol.get_ExplicitInterfaceImplementations()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SymbolExtensions.GetExplicitInterfaceImplementations(Symbol member)
   at Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol.MakeExplicitInterfaceImplementationMap()
   at Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol.GetExplicitImplementationForInterfaceMember(Symbol interfaceMember)
   at Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol.ComputeImplementationForInterfaceMember(Symbol interfaceMember, TypeSymbol implementingType, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol.ComputeImplementationAndDiagnosticsForInterfaceMember(Symbol interfaceMember)
   at Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol.FindImplementationForInterfaceMemberInNonInterfaceWithDiagnostics(Symbol interfaceMember)
   at Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol.FindImplementationForInterfaceMember(Symbol interfaceMember)
   at Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol.Microsoft.CodeAnalysis.ITypeSymbol.FindImplementationForInterfaceMember(ISymbol interfaceMember)
   at Analyzer.Utilities.Extensions.ISymbolExtensions.IsOverrideOrImplementationOfInterfaceMember(ISymbol symbol, ISymbol interfaceMember)
   at Microsoft.NetCore.Analyzers.Data.ReviewSqlQueriesForSecurityVulnerabilities.<>c__DisplayClass7_1.<Initialize>b__4(OperationAnalysisContext operationContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteOperationAction>b__54_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.
```

**Comment by mavasani** [comment]
@jinujoseph Can you please port this issue to Roslyn repo? Seems like an NRE in compiler layer, analyzer is just invoking a public API

**Comment by mavasani** [comment]
Duplicate of https://github.com/dotnet/roslyn/issues/33240
