### ISSUE TITLE
AD0001	Analyzer 'Microsoft.NetFramework.VisualBasic.Analyzers.BasicDoNotUseInsecureXSLTScriptExecutionAnalyzer

### ISSUE THREAD

**Issue by chewiiieee** [dotnet/roslyn-analyzers#2752]
#### Analyzer package
Microsoft.CodeAnalysis.FxCopAnalyzers
(https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version
v2.9.4 (Latest)

#### Diagnostic ID
Warning	AD0001	Analyzer 'Microsoft.NetFramework.VisualBasic.Analyzers.BasicDoNotUseInsecureXSLTScriptExecutionAnalyzer' threw an exception of type 'System.ArgumentOutOfRangeException' with message 'Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index'.	RptChecklistApp		1	Active

#### Repro steps
Create a file named whatever.vb and paste the following into it (using VS2019Ent 16.2.1)

Imports System.Xml.Xsl

Public Module Foobar
    Friend Sub foo()
        Dim internalSettings As New XsltSettings(True, False)
    End Sub
End Module

Public Class MDIMain
    Public Sub New()
    End Sub
End Class

#### Expected behavior
AD0001 AFAIK shouldn't be happening

#### Actual behavior
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD0001	Analyzer 'Microsoft.NetFramework.VisualBasic.Analyzers.BasicDoNotUseInsecureXSLTScriptExecutionAnalyzer' threw an exception of type 'System.ArgumentOutOfRangeException' with message 'Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index'.	RptChecklistApp		1	Active	Analyzer 'Microsoft.NetFramework.VisualBasic.Analyzers.BasicDoNotUseInsecureXSLTScriptExecutionAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: RptChecklist
SyntaxTree: C:\Users\hubertd\Documents\Source Code\Visual Studio 2019\source\rptChecklist\RptChecklistApp\foobar.vb
SyntaxNode: internalSettings As New XsltSettings ... [VariableDeclaratorSyntax]@[84..133) (5,12)-(5,61)

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.SZArrayHelper.get_Item[T](Int32 index)
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at Microsoft.NetFramework.Analyzers.DoNotUseInsecureXSLTScriptExecutionAnalyzer`1.SyntaxNodeAnalyzer.AnalyzeNodeForXsltSettings(SyntaxNodeAnalysisContext context)
   at Microsoft.NetFramework.Analyzers.DoNotUseInsecureXSLTScriptExecutionAnalyzer`1.SyntaxNodeAnalyzer.AnalyzeNode(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__50`1.<ExecuteSyntaxNodeAction>b__50_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.

[foobar.zip](https://github.com/dotnet/roslyn-analyzers/files/3486288/foobar.zip)

**Comment by chewiiieee** [comment]
Workaround:

Friend Sub foo()
        Dim internalSettings As New XsltSettings()
        internalSettings.EnableDocumentFunction = True
        internalSettings.EnableScript = False
End Sub

**Comment by dotpaul** [comment]
Thanks for reporting and the repro, @chewiiieee !
