### ISSUE TITLE
AD0001 SerializationRulesDiagnosticAnalyzer InvalidOperationException

### ISSUE THREAD

**Issue by nnpcYvIVl** [dotnet/roslyn-analyzers#2784]
Analyzer 'Microsoft.NetCore.Analyzers.Runtime.SerializationRulesDiagnosticAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'Sequence contains more than one element'.

See attached stacktrace. I'm using VS 16.2.3 and the latest version of the VSIX extension.

```
System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at System.Linq.ImmutableArrayExtensions.SingleOrDefault[T](ImmutableArray`1 immutableArray, Func`2 predicate)
   at Microsoft.NetCore.Analyzers.Runtime.SerializationRulesDiagnosticAnalyzer.SymbolAnalyzer.AnalyzeSymbol(SymbolAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteSymbolActionsCore>b__40_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
```

**Comment by mavasani** [comment]
Following should be changed to `FirstOrDefault`:

https://github.com/dotnet/roslyn-analyzers/blob/2a72252ddcd7c3ebbbb842239e67116a3678f610/src/Microsoft.NetCore.Analyzers/Core/Runtime/SerializationRulesDiagnosticAnalyzer.cs#L183
