### ISSUE TITLE
AD0001 (NullReferenceException)

### ISSUE THREAD

**Issue by cmenzi** [dotnet/roslyn-analyzers#3012]
#### Analyzer package

* Microsoft.NetCore.Analyzers.Security

#### Package Version

v2.9.7 (Latest)

#### Diagnostic ID

[AD0001]

#### Repro steps

Code that breaks analyzer:

```
public static string Calculate(string unhashedNameId)
{
    if (string.IsNullOrWhiteSpace(unhashedNameId))
    {
        throw new ArgumentNullException(nameof(unhashedNameId), $"{nameof(unhashedNameId)} must not be null, empty or whitespace.");
    }

    if (!Constants.UnhashedNameIdRegex.IsMatch(unhashedNameId))
    {
        throw new ArgumentException($"{nameof(unhashedNameId)} does not match '{Constants.UnhashedNameIdRegex}'.", nameof(unhashedNameId));
    }

    using (var sha = new SHA256Managed())
    {
        byte[] textData = Encoding.UTF8.GetBytes(unhashedNameId);
        byte[] crypto = sha.ComputeHash(textData);

        var nameId = new StringBuilder();
        foreach (byte hash in crypto)
        {
            nameId.Append(hash.ToString("x2", CultureInfo.InvariantCulture));
        }

        return nameId.ToString();
    }
}
```

#### Actual behavior

Exception:

```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Error	AD0001	Analyzer 'Microsoft.NetCore.Analyzers.Security.DoNotHardCodeCertificate' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	*** (netstandard2.0)		1	Active	Analyzer 'Microsoft.NetCore.Analyzers.Security.DoNotHardCodeCertificate' threw the following exception:
'Exception occurred with following context:
Compilation: ***
IOperation: Invocation
SyntaxTree: ***\NameIdentifier.cs
SyntaxNode: Encoding.UTF8.GetBytes(unhashedNameId ... [InvocationExpressionSyntax]@[1011..1049) (27,34)-(27,72)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Analyzer.Utilities.FlowAnalysis.Analysis.TaintedDataAnalysis.TaintedDataSymbolMapExtensions.<>c__DisplayClass0_0.<IsSourceMethod>b__5(IArgumentOperation o)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)
   at Analyzer.Utilities.FlowAnalysis.Analysis.TaintedDataAnalysis.TaintedDataSymbolMapExtensions.<>c__DisplayClass0_0.<IsSourceMethod>b__3(ValueTuple`2 s)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at Analyzer.Utilities.FlowAnalysis.Analysis.TaintedDataAnalysis.TaintedDataSymbolMapExtensions.IsSourceMethod(TaintedDataSymbolMap`1 sourceSymbolMap, IMethodSymbol method, ImmutableArray`1 arguments, Lazy`1 pointsToAnalysisResult, Lazy`1 valueContentAnalysisResult, PooledHashSet`1& allTaintedTargets)
   at Microsoft.NetCore.Analyzers.Security.SourceTriggeredTaintedDataAnalyzerBase.<>c__DisplayClass6_1.<Initialize>b__3(OperationAnalysisContext operationAnalysisContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteOperationAction>b__54_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.
```

**Comment by dotpaul** [comment]
Thanks for reporting, @cmenzi !

@LLLXXXCCC can you look at this one?

**Comment by dotpaul** [comment]
@cmenzi, did you see this issue in an open source repository you can point us to?
