### ISSUE TITLE
AD0001 (NullReferenceException) Microsoft.NetCore.Analyzers.Data.ReviewSqlQueriesForSecurityVulnerabilities 

### ISSUE THREAD

**Issue by leung85** [dotnet/roslyn-analyzers#3086]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version
Microsoft Code Analysis 2019 v3.0.0.1925803

#### Problem code

```
public async Task<UserDTO> AuthenticationTest(string name, string password)
        {
               ApplicationUser user = await _userManager.FindByNameAsync(name);

                return user is null
                    ? null
                    : new UserDTO()
                    {
                        Name = user.UserName,
                        Roles = user.Roles
                    };
        }
```

#### Expected behavior
No null reference exceptions

#### Actual behavior

```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD0001	Analyzer 'Microsoft.NetCore.Analyzers.Data.ReviewSqlQueriesForSecurityVulnerabilities' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.			1	Active	Analyzer 'Microsoft.NetCore.Analyzers.Data.ReviewSqlQueriesForSecurityVulnerabilities' threw the following exception:
'Exception occurred with following context:
IOperation: PropertyReference
SyntaxNode: user.UserName [MemberAccessExpressionSyntax]@[1454..1467) (41,31)-(41,44)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Analyzer.Utilities.Extensions.ISymbolExtensions.IsOverrideOrImplementationOfInterfaceMember(ISymbol symbol, ISymbol interfaceMember)
   at Analyzer.Utilities.Extensions.ISymbolExtensions.IsOverrideOrImplementationOfInterfaceMember(ISymbol symbol, ISymbol interfaceMember)
   at Microsoft.NetCore.Analyzers.Data.ReviewSqlQueriesForSecurityVulnerabilities.<>c__DisplayClass7_1.<Initialize>b__4(OperationAnalysisContext operationContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteOperationAction>b__54_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.
```

**Comment by leung85** [comment]
After update to Visual Studio 16.4.1, the warning gone
