### ISSUE TITLE
Intermittent test failure in Spanish queue

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#3166]
See https://dev.azure.com/dnceng/public/_build/results?buildId=475513&view=ms.vss-test-web.build-test-results-tab&runId=15125436&resultId=104047&paneView=debug

**Test Name:** `ArgumentNullException_NoArguments_Warns`

**Error Message:**
```
Microsoft.CodeAnalysis.Testing.Verifiers.EqualWithMessageException : Context: Diagnostics of test state\r\nExpected diagnostic message to be "Call the ArgumentNullException constructor that contains a message and/or paramName parameter." was "Llame al constructor ArgumentNullException que contiene un mensaje o un parámetro paramName."\r\n\r\nDiagnostic:\r\n // Test0.vb(4,31): warning CA2208: Llame al constructor ArgumentNullException que contiene un mensaje o un parámetro paramName.\r\nGetBasicResultAt(4, 31, InstantiateArgumentExceptionsCorrectlyAnalyzer.CA2208)\r\n\r\n\r\nAssert.Equal() Failure\r\nExpected: Call the ArgumentNullException constructor that contains a message and/or paramName parameter.\r\nActual: Llame al constructor ArgumentNullException que contiene un mensaje o un parámetro paramName.
```

**Stack:**
```
at Microsoft.CodeAnalysis.Testing.Verifiers.XUnitVerifier.Equal[T](T expected, T actual, String message) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Testing.Verifiers.XUnit/XUnitVerifier.cs:line 48
   at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.VerifyDiagnosticResults(IEnumerable`1 actualResults, ImmutableArray`1 analyzers, DiagnosticResult[] expectedResults, IVerifier verifier) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs:line 316
   at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.<VerifyDiagnosticsAsync>d__55.MoveNext() in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs:line 197
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.<RunAsync>d__38.MoveNext() in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 189
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Test.Utilities.VisualBasicCodeFixVerifier`2.<VerifyAnalyzerAsync>d__4.MoveNext() in F:\workspace\_work\1\s\src\Test.Utilities\VisualBasicCodeFixVerifier`2.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.NetCore.Analyzers.Runtime.UnitTests.InstantiateArgumentExceptionsCorrectlyTests.<ArgumentNullException_NoArguments_Warns>d__9.MoveNext() in F:\workspace\_work\1\s\src\NetAnalyzers\UnitTests\Microsoft.NetCore.Analyzers\Runtime\InstantiateArgumentExceptionsCorrectlyTests.cs:line 172
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by mavasani** [comment]
Tagging @Evangelink @sharwell
