### ISSUE TITLE
Crash in DisposableFieldsShouldBeDisposed when cancelling build

### ISSUE THREAD

**Issue by mayerj** [dotnet/roslyn-analyzers#3238]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.7

#### Diagnostic ID

CA2212 Microsoft.NetCore.Analyzers.Runtime.DisposableFieldsShouldBeDisposed

#### Repro steps

Unknown crash when cancelling build

#### Expected behavior

No AD0001 crash

#### Actual behavior

Error	AD0001	Analyzer 'Microsoft.NetCore.Analyzers.Runtime.DisposableFieldsShouldBeDisposed' threw an exception of type 'System.OperationCanceledException' with message 'The operation was canceled.'.	[redacted]		1	Active	Analyzer 'Microsoft.NetCore.Analyzers.Runtime.DisposableFieldsShouldBeDisposed' threw the following exception:
'Exception occurred with following context:
Compilation: [redacted]
IOperation: FieldInitializer
SyntaxTree: [redacted]
SyntaxNode: = null [EqualsValueClauseSyntax]@[1189..1195) (27,24)-(27,30)

System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.CodeAnalysis.Host.RecoverableWeakValueSource`1.GetValue(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.RecoverableTextAndVersion.GetValue(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.TextDocumentState.GetTextSynchronously(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.AdditionalTextWithState.GetText(CancellationToken cancellationToken)
   at Analyzer.Utilities.AnalyzerOptionsExtensions.<>c__DisplayClass16_0.<GetOrComputeCategorizedAnalyzerConfigOptions>g__ComputeCategorizedAnalyzerConfigOptions|1()
   at Analyzer.Utilities.AnalyzerOptionsExtensions.<>c__DisplayClass16_0.<GetOrComputeCategorizedAnalyzerConfigOptions>b__0(AnalyzerOptions _)
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.GetValue(TKey key, CreateValueCallback createValueCallback)
   at Analyzer.Utilities.AnalyzerOptionsExtensions.GetOrComputeCategorizedAnalyzerConfigOptions(AnalyzerOptions options, CancellationToken cancellationToken)
   at Analyzer.Utilities.AnalyzerOptionsExtensions.GetSymbolNamesOption(AnalyzerOptions options, String optionName, String namePrefixOpt, DiagnosticDescriptor rule, Compilation compilation, CancellationToken cancellationToken)
   at Analyzer.Utilities.Extensions.ISymbolExtensions.IsConfiguredToSkipAnalysis(ISymbol symbol, AnalyzerOptions options, DiagnosticDescriptor rule, Compilation compilation, CancellationToken cancellationToken)
   at Microsoft.NetCore.Analyzers.Runtime.DisposableFieldsShouldBeDisposed.<>c__DisplayClass7_0.<Initialize>g__ShouldAnalyze|6(INamedTypeSymbol namedType)
   at Microsoft.NetCore.Analyzers.Runtime.DisposableFieldsShouldBeDisposed.<>c__DisplayClass7_0.<Initialize>b__3(OperationAnalysisContext operationContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteOperationAction>b__56_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)

**Comment by mavasani** [comment]
@mayerj Which version of VS are you using? I have seen this exception very recently on latest VS 2019 16.5 Preview builds as well, and I am wondering if this is a regression in Roslyn.

**Comment by mayerj** [comment]
Microsoft Visual Studio Enterprise 2019
Version 16.4.3

**Comment by mavasani** [comment]
Thanks. I think I see the bug in the analyzer. Will send a PR to fix it soon.

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn-analyzers/pull/3239
