### ISSUE TITLE
Invalid cast exception in UseCountProperlyAnalyzer

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#3724]
#### Analyzer package

Used the latest `Microsoft.CodeAnalysis.NetAnalyzers` from https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json

#### Package Version

3.3.0-beta1.20305.4 (Latest) OR build the latest source from Roslyn analyzers repo

#### Exception

```
Severity	Code	Description	File	Suppression State	Project	Line	Source	Detail Description
Error	AD0001	Analyzer 'Microsoft.NetCore.Analyzers.Performance.UseCountProperlyAnalyzer' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.Operations.CSharpLazyPropertyReferenceOperation' to type 'Microsoft.CodeAnalysis.Operations.IInvocationOperation'.'.
Exception occurred with following context:
Compilation: Microsoft.CodeAnalysis
IOperation: PropertyReference
SyntaxTree: c:\roslyn\src\Compilers\Core\Portable\FileSystem\PathUtilities.cs
SyntaxNode: parentPath.Length [MemberAccessExpressionSyntax]@[20641..20658) (568,110)-(568,127)

System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.Operations.CSharpLazyPropertyReferenceOperation' to type 'Microsoft.CodeAnalysis.Operations.IInvocationOperation'.
   at Microsoft.NetCore.Analyzers.Performance.UseCountProperlyAnalyzer.AnalyzePropertyReference(OperationAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteOperationAction>b__59_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: CA1827, CA1828, CA1829, CA1836		Active	Microsoft.CodeAnalysis (netcoreapp3.1)	1	IntelliSense	Analyzer 'Microsoft.NetCore.Analyzers.Performance.UseCountProperlyAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: Microsoft.CodeAnalysis
IOperation: PropertyReference
SyntaxTree: c:\roslyn\src\Compilers\Core\Portable\FileSystem\PathUtilities.cs
SyntaxNode: parentPath.Length [MemberAccessExpressionSyntax]@[20641..20658) (568,110)-(568,127)

System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.Operations.CSharpLazyPropertyReferenceOperation' to type 'Microsoft.CodeAnalysis.Operations.IInvocationOperation'.
   at Microsoft.NetCore.Analyzers.Performance.UseCountProperlyAnalyzer.AnalyzePropertyReference(OperationAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteOperationAction>b__59_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.
Error	AD0001	Analyzer 'Microsoft.NetCore.Analyzers.Performance.UseCountProperlyAnalyzer' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.Operations.CSharpLazyObjectCreationOperation' to type 'Microsoft.CodeAnalysis.Operations.IInvocationOperation'.'.
Exception occurred with following context:
Compilation: Microsoft.CodeAnalysis
IOperation: PropertyReference
SyntaxTree: c:\roslyn\src\Compilers\Core\Portable\Syntax\SyntaxDiffer.cs
SyntaxNode: after!.GetText().Length [MemberAccessExpressionSyntax]@[3399..3422) (82,47)-(82,70)

System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.Operations.CSharpLazyObjectCreationOperation' to type 'Microsoft.CodeAnalysis.Operations.IInvocationOperation'.
   at Microsoft.NetCore.Analyzers.Performance.UseCountProperlyAnalyzer.AnalyzePropertyReference(OperationAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteOperationAction>b__59_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: CA1827, CA1828, CA1829, CA1836		Active	Microsoft.CodeAnalysis (netcoreapp3.1)	1	IntelliSense
```

**Comment by mavasani** [comment]
@Jozkee I am seeing this exception in Roslyn.sln after moving to latest analyzer package.

**Comment by mavasani** [comment]
I think you can repro this by following steps:

1. Set `Microsoft.CodeAnalysis.NetAnalyzers.Setup` as startup project in RoslynAnalyzers.sln and click F5
2. Open Roslyn.sln in the VS instance that was started and open `src\Compilers\Core\Portable\FileSystem\PathUtilities.cs`. Note you may have to run `restore.cmd` from the root of the Roslyn repo before opening the solution.

Let me know if you need reproing this issue.
