### ISSUE TITLE
PlatformCompatibilityAnalyzer throws System.ArgumentException

### ISSUE THREAD

**Issue by davidkarlsson** [dotnet/roslyn-analyzers#4372]
### Analyzer

**Diagnostic ID**: [CA1416](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/CA1416): `Validate platform compatibility`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 5 SDK or later](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [5.0.100-rc.2.20479.15](https://dotnet.microsoft.com/download/dotnet/5.0)

### Describe the bug

If you are on Windows and call a method with a `[SupportedOSPlatform("windows")]` attribute in a loop that checks that you can call it with a `OperatingSystem.IsWindows()` condition a `ArgumentException` exception will be thrown with the message: `'An element with the same key but a different value already exists. Key: 'Microsoft.CodeAnalysis.Operations.FlowCaptureReferenceOperation''`. If you instead call the method outside of the loop the exception is not thrown.

### Steps To Reproduce
Here's a small repro I think:

```csharp
using System;
using System.Runtime.Versioning;

namespace AnalyzerTest
{
    class Program
    {
        static void Main(string[] args)
        {
            for (var i = 0; i < 2; i++)
            {
                if (OperatingSystem.IsWindows())
                {
                    WindowsSupported();
                }
            }
        }

        [SupportedOSPlatform("windows")]
        public static void WindowsSupported()
        {
            Console.WriteLine("Windows");
        }
    }
}
```
### Expected behavior
I didn't expect this to throw an `ArgumentException` just because the method is called from a loop.

### Actual behavior
`PlatformCompatibilityAnalyzer` throws an `ArgumentException` which get logged as a AD0001 warning on build.

## Additional context
Here's a stack trace of exception that PlatformCompatibilityAnalyzer throws in this scenario:
```
Warning	AD0001	Analyzer 'Microsoft.NetCore.Analyzers.InteropServices.PlatformCompatibilityAnalyzer' threw an exception of type 'System.ArgumentException' with message 'An element with the same key but a different value already exists. Key: 'Microsoft.CodeAnalysis.Operations.FlowCaptureReferenceOperation''.
Exception occurred with following context:
Compilation: Test
ISymbol: TestAsync (Method)

System.ArgumentException: An element with the same key but a different value already exists. Key: 'Microsoft.CodeAnalysis.Operations.FlowCaptureReferenceOperation'
   at System.Collections.Immutable.ImmutableDictionary`2.HashBucket.Add(TKey key, TValue value, IEqualityComparer`1 keyOnlyComparer, IEqualityComparer`1 valueComparer, KeyCollisionBehavior behavior, OperationResult& result)
   at System.Collections.Immutable.ImmutableDictionary`2.Add(TKey key, TValue value, KeyCollisionBehavior behavior, MutationInput origin)
   at System.Collections.Immutable.ImmutableDictionary`2.Builder.Add(TKey key, TValue value)
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.GlobalFlowStateAnalysis.GlobalFlowStateDataFlowOperationVisitor.Visit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.DataFlowOperationVisitor`4.VisitArray(IEnumerable`1 operations, Object argument)
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.DataFlowOperationVisitor`4.VisitInvocation_NonLambdaOrDelegateOrLocalFunction(IInvocationOperation operation, Object argument)
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.DataFlowOperationVisitor`4.VisitInvocation(IInvocationOperation operation, Object argument)
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.DataFlowOperationVisitor`4.VisitCore(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.DataFlowOperationVisitor`4.Visit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.GlobalFlowStateAnalysis.GlobalFlowStateDataFlowOperationVisitor.Visit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.DataFlowOperationVisitor`4.FlowBranch(BasicBlock fromBlock, BranchWithInfo branch, TAnalysisData input)
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.GlobalFlowStateAnalysis.GlobalFlowStateDataFlowOperationVisitor.FlowBranch(BasicBlock fromBlock, BranchWithInfo branch, DictionaryAnalysisData`2 input)
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.DataFlowAnalysis`5.RunCore(ControlFlowGraph cfg, PooledSortedSet`1 worklist, PooledSortedSet`1 pendingBlocksNeedingAtLeastOnePass, TAnalysisData initialAnalysisData, DataFlowAnalysisResultBuilder`1 resultBuilder, PooledHashSet`1 uniqueSuccessors, PooledDictionary`2 finallyBlockSuccessorsMap, PooledDictionary`2 catchBlockInputDataMap, PooledDictionary`2 inputDataFromInfeasibleBranchesMap, PooledDictionary`2 blockToUniqueInputFlowMap, PooledDictionary`2 loopRangeMap, Boolean exceptionPathsAnalysisPostPass)
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.DataFlowAnalysis`5.Run(TAnalysisContext analysisContext)
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.GlobalFlowStateAnalysis.GlobalFlowStateAnalysis.TryGetOrComputeResult(ControlFlowGraph cfg, ISymbol owningSymbol, Func`2 createOperationVisitor, WellKnownTypeProvider wellKnownTypeProvider, AnalyzerOptions analyzerOptions, InterproceduralAnalysisConfiguration interproceduralAnalysisConfig, InterproceduralAnalysisPredicate interproceduralAnalysisPredicate, PointsToAnalysisKind pointsToAnalysisKind, Boolean pessimisticAnalysis, Boolean performValueContentAnalysis, DataFlowAnalysisResult`2& valueContentAnalysisResult, ImmutableArray`1 additionalSupportedValueTypes, Func`2 getValueContentValueForAdditionalSupportedValueTypeOperation)
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.GlobalFlowStateAnalysis.GlobalFlowStateAnalysis.TryGetOrComputeResult(ControlFlowGraph cfg, ISymbol owningSymbol, Func`2 createOperationVisitor, WellKnownTypeProvider wellKnownTypeProvider, AnalyzerOptions analyzerOptions, DiagnosticDescriptor rule, Boolean performValueContentAnalysis, Boolean pessimisticAnalysis, CancellationToken cancellationToken, DataFlowAnalysisResult`2& valueContentAnalysisResult, InterproceduralAnalysisKind interproceduralAnalysisKind, InterproceduralAnalysisPredicate interproceduralAnalysisPredicate, ImmutableArray`1 additionalSupportedValueTypes, Func`2 getValueContentValueForAdditionalSupportedValueTypeOperation)
   at Microsoft.NetCore.Analyzers.InteropServices.PlatformCompatibilityAnalyzer.<>c__DisplayClass23_0.<AnalyzeOperationBlock>b__1(OperationBlockAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__67`2.<ExecuteBlockActions>b__67_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: CA1416	Test		1	Active
```

**Comment by mavasani** [comment]
Thanks, I will investigate.

**Comment by mavasani** [comment]
The fix should be just changing the below `Add` call to a dictionary write, i.e. `_globalValuesMapBuilder[operation] = GlobalState;` https://github.com/dotnet/roslyn-analyzers/blob/a235f3f23323cd0508d08d7702e3b92faef3cf55/src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/GlobalFlowStateAnalysis/GlobalFlowStateDataFlowOperationVisitor.cs#L208

Tag @buyaa-n as well.

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn-analyzers/pull/4393
