### ISSUE TITLE
NullReferenceException in RS1024

### ISSUE THREAD

**Issue by meziantou** [dotnet/roslyn-analyzers#4470]
### Analyzer

**Diagnostic ID**: RS1024

### Analyzer source

````
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.1" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="3.8.0" PrivateAssets="all" />
````

### Describe the bug

````
Severity	Code	Description	Project	File	Line	Suppression State
Warning	AD0001	Analyzer 'Microsoft.CodeAnalysis.Analyzers.MetaAnalyzers.CompareSymbolsCorrectlyAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
Exception occurred with following context:
Compilation: Meziantou.Analyzer
IOperation: ObjectCreation
SyntaxTree: C:\Users\mezia\source\repos\Meziantou.Analyzer\src\Meziantou.Analyzer\Rules\MakeMethodStaticAnalyzer.cs
SyntaxNode: new(SymbolEqualityComparer.Default ... [ImplicitObjectCreationExpressionSyntax]@[2425..2460) (55,66)-(55,101)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.Analyzers.MetaAnalyzers.CompareSymbolsCorrectlyAnalyzer.<>c__DisplayClass15_0.<HandleObjectCreation>b__0(IArgumentOperation arg)
   at System.Linq.ImmutableArrayExtensions.Any[T](ImmutableArray`1 immutableArray, Func`2 predicate)
   at Microsoft.CodeAnalysis.Analyzers.MetaAnalyzers.CompareSymbolsCorrectlyAnalyzer.HandleObjectCreation(OperationAnalysisContext& context, INamedTypeSymbol symbolType, INamedTypeSymbol symbolEqualityComparerType, ImmutableHashSet`1 collectionTypes)
   at Microsoft.CodeAnalysis.Analyzers.MetaAnalyzers.CompareSymbolsCorrectlyAnalyzer.<>c__DisplayClass12_1.<Initialize>b__3(OperationAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteOperationAction>b__63_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: RS1024	Meziantou.Analyzer		1	Active
````

### Steps To Reproduce

1. Clone https://github.com/meziantou/Meziantou.Analyzer/
2. Checkout f93959b7efc062118db672f4acab177bf1deb846 (currently, the latest commit on this PR https://github.com/meziantou/Meziantou.Analyzer/pull/208)
3. Open the solution in Visual Studio

### Expected behavior

RS1024 doesn't crash

### Actual behavior

RS1024 crashes

**Comment by Evangelink** [comment]
I have found the line where it fails but I am not sure how to repro the case.

**Comment by mavasani** [comment]
@Evangelink possibly can be repro'ed by opening https://github.com/meziantou/Meziantou.Analyzer?

**Comment by mavasani** [comment]
File to open in that repo: `MakeMethodStaticAnalyzer.cs`
NOTE: You will need to attach the debugger to the RoslynCodeAnalysis ServiceHub process, not devenv.exe as analyzers now run in this separate process while typing in the IDE.
