### ISSUE TITLE
CompareSymbolsCorrectlyFix InvalidCastException

### ISSUE THREAD

**Issue by Kuinox** [dotnet/roslyn-analyzers#5091]
### Analyzer

**Diagnostic ID**: RS1024.

### Analyzer source

**Version**: 6.0.100-preview.4.21220.4

### Steps To Reproduce

```csharp
INamedTypeSymbol? attributeType = null;
ImmutableArray<AttributeData> attributes = default;
attributes.Where( s => s.AttributeClass?.Equals( attributeType ) ?? false );
```
Summon codefix on .Equals will throw:
<details><summary>stacktrace</summary>
<p>

```csharp
System.InvalidCastException : Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.MemberAccessExpressionSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.ParameterSyntax'.
   at System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.SeparatedList[TNode](IEnumerable`1 nodes)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.AsParameterList(IEnumerable`1 parameters)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.InsertParameters(SyntaxNode declaration,Int32 index,IEnumerable`1 parameters)
   at Microsoft.CodeAnalysis.Editing.SyntaxGenerator.AddParameters(SyntaxNode declaration,IEnumerable`1 parameters)
   at async Microsoft.CodeAnalysis.Analyzers.MetaAnalyzers.Fixers.CompareSymbolsCorrectlyFix.EnsureEqualsCorrectAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Analyzers.MetaAnalyzers.Fixers.CompareSymbolsCorrectlyFix.ConvertToEqualsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

</p>

**Comment by Kuinox** [comment]
Where the analyzer is supposed to be?
In VS ? In the SDK ? In the package nuget ?  
![image](https://user-images.githubusercontent.com/18743295/117698114-a0d53b00-b1c3-11eb-98b3-790fa058ff9b.png)
My dependencies looks up to date.

**Comment by Youssef1313** [comment]
> Where the analyzer is supposed to be?
> In VS ? In the SDK ? In the package nuget ?

You can consume analyzers from either the SDK or from the NuGet package.
It's unclear from the screenshot what version of Microsoft.CodeAnalysis.NetAnalyzers you're using, or if you're consuming it from the SDK.

**Comment by Kuinox** [comment]
Ok, I updated, now there is still the warning, but no more codefix.
![image](https://user-images.githubusercontent.com/18743295/117729015-84002e00-b1ea-11eb-8dfc-b0f558a6e49b.png)

**Comment by mavasani** [comment]
`Microsoft.CodeAnalysis.NetAnalyzers` is not the package that contains `CompareSymbolsCorrectly` analyzer/fix. You should instead try to add a NuGet package reference to `Microsoft.CodeAnalysis.Analyzers` from this feed: https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet6&package=Microsoft.CodeAnalysis.Analyzers&protocolType=NuGet&version=3.3.3-beta1.21256.2&view=versions

**Comment by Youssef1313** [comment]
> `Microsoft.CodeAnalysis.NetAnalyzers` is not the package that contains `CompareSymbolsCorrectly` analyzer/fix. You should instead try to add a NuGet package reference to `Microsoft.CodeAnalysis.Analyzers` from this feed: https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet6&package=Microsoft.CodeAnalysis.Analyzers&protocolType=NuGet&version=3.3.3-beta1.21256.2&view=versions

Oh. Sorry for any confusion above @Kuinox

**Comment by Youssef1313** [comment]
@mavasani Was this closed by mistake? This is now complaining that no codefix is being offered.
