### ISSUE TITLE
Attempt to load abstract code fix results in an exception

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn-analyzers#5335]
roslyn-analyzers has an exported abstract CodeFix class with a derived concrete class:
https://github.com/dotnet/roslyn-analyzers/commit/cb17df3f04d2d9a444665ad85bae293a8850ddb8

The logic to load code fix types doesn't check whether the type is abstract:
https://github.com/dotnet/roslyn/blob/159cb67bb1e38f12662b22681e412c9746e7bcfb/src/Features/Core/Portable/Common/AbstractProjectExtensionProvider%602.cs#L59

This results in MissingMethodException:

```
System.MissingMethodException: Cannot create an abstract class.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
```

FYI @MeikTranel @sharwell

**Comment by MeikTranel** [comment]
Yep I'll get that asap when I'm home.

**Comment by MeikTranel** [comment]
@sharwell want me to target main or any of the release branches?

**Comment by mavasani** [comment]
Fixed in release branch.
