### ISSUE TITLE
Code AD0001 - Analyzer CA2252 - Analyzer 'Microsoft.NetCore.Analyzers.Runtime.DetectPreviewFeatureAnalyzer' threw an exception of type 'System.ArgumentNullException'

### ISSUE THREAD

**Issue by ryanbuening** [dotnet/roslyn-analyzers#5482]
After updating to .NET 6 RC1 I'm receiving the following error (I have `<TreatWarningsAsErrors>true</TreatWarningsAsErrors>` in my csproj) in multiple places in my Blazor app:

```
Analyzer 'Microsoft.NetCore.Analyzers.Runtime.DetectPreviewFeatureAnalyzer' threw an exception of type 'System.ArgumentNullException' with message 'Value cannot be null.
Parameter name: key'.
Exception occurred with following context:
IOperation: PropertyReference
SyntaxNode: ApiKey [IdentifierNameSyntax]@[827..833) (33,15)-(33,21)

System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryGetValue(TKey key, TValue& value)
   at Microsoft.NetCore.Analyzers.Runtime.DetectPreviewFeatureAnalyzer.SymbolIsAnnotatedAsPreview(ISymbol symbol, ConcurrentDictionary`2 requiresPreviewFeaturesSymbols, INamedTypeSymbol previewFeatureAttribute)
   at Microsoft.NetCore.Analyzers.Runtime.DetectPreviewFeatureAnalyzer.SymbolIsAnnotatedOrUsesPreviewTypes(ISymbol symbol, ConcurrentDictionary`2 requiresPreviewFeaturesSymbols, INamedTypeSymbol previewFeatureAttributeSymbol, ISymbol& referencedPreviewSymbol)
   at Microsoft.NetCore.Analyzers.Runtime.DetectPreviewFeatureAnalyzer.OperationUsesPreviewFeatures(OperationAnalysisContext context, ConcurrentDictionary`2 requiresPreviewFeaturesSymbols, INamedTypeSymbol previewFeatureAttributeSymbol, ISymbol& referencedPreviewSymbol)
   at Microsoft.NetCore.Analyzers.Runtime.DetectPreviewFeatureAnalyzer.BuildSymbolInformationFromOperations(OperationAnalysisContext context, ConcurrentDictionary`2 requiresPreviewFeaturesSymbols, INamedTypeSymbol previewFeatureAttributeSymbol)
   at Microsoft.NetCore.Analyzers.Runtime.DetectPreviewFeatureAnalyzer.<>c__DisplayClass26_0.<Initialize>b__1(OperationAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteOperationAction>b__63_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: CA2252
```

@pgovind

**Comment by DavidArno** [comment]
@mavasani, something strange is happening here. It says you added this to the .NET 6.x milestone 8 days ago, but the milestone on the right says .NET 7.0 and the link for .NET 6.x takes me to the .NET 7 milestone. 😕

**Comment by pgovind** [comment]
I missed this notification in my emails. Can you post a sample that reproduces the bug please? I recently fixed a crash related to getters that had the same call stack, so this might be fixed already.

**Comment by ryanbuening** [comment]
@pgovind sample [here](https://github.com/ryanbuening/ca2252-error).

**Comment by pgovind** [comment]
Thanks for the sample @ryanbuening. I fixed that bug last week with https://github.com/dotnet/roslyn-analyzers/pull/5470. If you get a chance to use the latest daily bits, you should see it fixed! I'm going to optimistically close this issue, but if the crash still occurs on your machine, please do re-open it!

**Comment by mavasani** [comment]
> It says you added this to the .NET 6.x milestone 8 days ago, but the milestone on the right says .NET 7.0

.NET 6.0 is in lockdown mode now, so I renamed the .NET 6.0 milestone to .NET 7.0 to bulk move existing issues to the next major release. I'll create a new .NET 6.x milestone for any high priority servicing bugs.
