### ISSUE TITLE
TestCodeFixToEnableAnalyzerReleaseTrackingAsync is flaky

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn-analyzers#5589]
Error Message

```
System.AggregateException : One or more errors occurred. (Unexpected Null)\n---- System.InvalidOperationException : Unexpected Null
```

Stack Trace:
```
   at Microsoft.CodeAnalysis.Host.RecoverableWeakValueSource`1.GetValueAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.RecoverableTextAndVersion.GetValueAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.TextDocumentState.GetTextAndVersionAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.TextDocumentState.GetTextAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.VerifyProjectAsync(ProjectState newState, Project project, IVerifier verifier, CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 499
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.VerifyFixAsync(String language, ImmutableArray`1 analyzers, ImmutableArray`1 codeFixProviders, SolutionState oldState, SolutionState newState, Int32 numberOfIterations, Func`10 getFixedProject, IVerifier verifier, CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 465
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.VerifyFixAsync(SolutionState testState, SolutionState fixedState, SolutionState batchFixedState, IVerifier verifier, CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 429
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.RunImplAsync(CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 274
   at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.RunAsync(CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs:line 180
   at Microsoft.CodeAnalysis.Analyzers.UnitTests.MetaAnalyzers.ReleaseTrackingAnalyzerTests.TestCodeFixToEnableAnalyzerReleaseTrackingAsync() in /_/src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/ReleaseTrackingAnalyzerTests.cs:line 100
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at Roslyn.Utilities.Contract.Fail(String message)
   at Roslyn.Utilities.Contract.ThrowIfNull[T](T value, String message)
   at Microsoft.CodeAnalysis.RecoverableTextAndVersion.RecoverableText.RecoverAsync(CancellationToken cancellationToken)
```

[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1399768)

**Comment by Youssef1313** [comment]
@jmarolf I recall this is a roslyn bug that @sharwell has fixed in past. But we're using lots of old MS.CA packages.

**Comment by Youssef1313** [comment]
https://github.com/dotnet/roslyn-analyzers/pull/4853#issuecomment-779956198

**Comment by sharwell** [comment]
@jmarolf this should be fixed in Roslyn 3.10. Can you verify which version of Roslyn was running for this test?

**Comment by jmarolf** [comment]
We previously hard-locked to the 3.9 version of the compilers. I recently updated this in main: https://github.com/dotnet/roslyn-analyzers/commit/fc5d24276245cc06c445442bfde660af98ba45a4

**Comment by sharwell** [comment]
That's the version of the compiler we use to build the code, but not the version of the compiler we use for executing the tests. We still execute the tests with 3.3.1:

https://github.com/dotnet/roslyn-analyzers/blob/d7403510f2aac1a0c9059ab7208e68b0b27e1849/eng/Versions.props#L45

**Comment by sharwell** [comment]
All 7 failures of this test in the past 14 days have occurred on Ubuntu test runs. The viable options to fix appear to be:

* Update this test leg to use a newer version of Roslyn (to match others we've already updated)
* Exclude this test on Ubuntu
* Implement retry logic within this test, where if it fails the first time it automatically runs a second time to see if it passes

**Comment by jmarolf** [comment]
> Update this test leg to use a newer version of Roslyn

I assume we can use a newer version of the compiler in the test runs without updating the supported minimum version of the compiler?

**Comment by sharwell** [comment]
> I assume we can use a newer version of the compiler in the test runs without updating the supported minimum version of the compiler?

Yes, but we lose test coverage for older versions.
