### ISSUE TITLE
Publishing is failing in Official Builds

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn-analyzers#5671]
See Pipeline - https://dev.azure.com/dnceng/internal/_build?definitionId=830&_a=summary (microsoft only)

Latest Build - https://dev.azure.com/dnceng/internal/_build/results?buildId=1433878&view=logs&j=ba23343f-f710-5af9-782d-5bd26b102304&t=6e277ba4-1c1e-552d-b96f-db0aeb4be20a (microsoft only)

```
  Successfully published to symbol servers.
  Publishing pdbFiles to https://microsoftpublicsymbols.artifacts.visualstudio.com/DefaultCollection:
  Publishing pdbFiles to https://microsoft.artifacts.visualstudio.com/DefaultCollection:
  Successfully published pdb files
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.21518.6\tools\SdkTasks\PublishArtifactsInManifest.proj(139,5): error : The specified blob already exists.
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.21518.6\tools\SdkTasks\PublishArtifactsInManifest.proj(139,5): error : RequestId:fef8fd9b-e01e-010f-3342-c60368000000
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.21518.6\tools\SdkTasks\PublishArtifactsInManifest.proj(139,5): error : Time:2021-10-21T06:10:33.4923049Z
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.21518.6\tools\SdkTasks\PublishArtifactsInManifest.proj(139,5): error : Status: 409 (The specified blob already exists.)
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.21518.6\tools\SdkTasks\PublishArtifactsInManifest.proj(139,5): error : ErrorCode: BlobAlreadyExists
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.21518.6\tools\SdkTasks\PublishArtifactsInManifest.proj(139,5): error : 
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.21518.6\tools\SdkTasks\PublishArtifactsInManifest.proj(139,5): error : Headers:
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.21518.6\tools\SdkTasks\PublishArtifactsInManifest.proj(139,5): error : Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.21518.6\tools\SdkTasks\PublishArtifactsInManifest.proj(139,5): error : x-ms-request-id: fef8fd9b-e01e-010f-3342-c60368000000
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.21518.6\tools\SdkTasks\PublishArtifactsInManifest.proj(139,5): error : x-ms-client-request-id: 1a223f87-336c-4954-9b23-05b4dcbbc398
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.21518.6\tools\SdkTasks\PublishArtifactsInManifest.proj(139,5): error : x-ms-version: 2019-07-07
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.21518.6\tools\SdkTasks\PublishArtifactsInManifest.proj(139,5): error : x-ms-error-code: BlobAlreadyExists
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.21518.6\tools\SdkTasks\PublishArtifactsInManifest.proj(139,5): error : Date: Thu, 21 Oct 2021 06:10:32 GMT
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.21518.6\tools\SdkTasks\PublishArtifactsInManifest.proj(139,5): error : Content-Length: 220
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.21518.6\tools\SdkTasks\PublishArtifactsInManifest.proj(139,5): error : Content-Type: application/xml
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.21518.6\tools\SdkTasks\PublishArtifactsInManifest.proj(139,5): error : 
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.21518.6\tools\SdkTasks\PublishArtifactsInManifest.proj(139,5): error :    at Azure.Storage.Blobs.BlobRestClient.BlockBlob.UploadAsync_CreateResponse(ClientDiagnostics clientDiagnostics, Response response)
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.21518.6\tools\SdkTasks\PublishArtifactsInManifest.proj(139,5): error :    at Azure.Storage.Blobs.BlobRestClient.BlockBlob.UploadAsync(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri resourceUri, Stream body, Int64 contentLength, String version, Nullable`1 timeout, Byte[] transactionalContentHash, String blobContentType, String blobContentEncoding, String blobContentLanguage, Byte[] blobContentHash, String blobCacheControl, IDictionary`2 metadata, String leaseId, String blobContentDisposition, String encryptionKey, String encryptionKeySha256, Nullable`1 encryptionAlgorithm, String encryptionScope, Nullable`1 tier, Nullable`1 ifModifiedSince, Nullable`1 ifUnmodifiedSince, Nullable`1 ifMatch, Nullable`1 ifNoneMatch, String requestId, Boolean async, String operationName, CancellationToken cancellationToken)
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.21518.6\tools\SdkTasks\PublishArtifactsInManifest.proj(139,5): error :    at Azure.Storage.Blobs.Specialized.BlockBlobClient.UploadInternal(Stream content, BlobHttpHeaders blobHttpHeaders, IDictionary`2 metadata, BlobRequestConditions conditions, Nullable`1 accessTier, IProgress`1 progressHandler, String operationName, Boolean async, CancellationToken cancellationToken)
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.21518.6\tools\SdkTasks\PublishArtifactsInManifest.proj(139,5): error :    at Azure.Storage.Blobs.PartitionedUploader.UploadAsync(Stream content, BlobHttpHeaders blobHttpHeaders, IDictionary`2 metadata, BlobRequestConditions conditions, IProgress`1 progressHandler, Nullable`1 accessTier, CancellationToken cancellationToken)
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.21518.6\tools\SdkTasks\PublishArtifactsInManifest.proj(139,5): error :    at Azure.Storage.Blobs.BlobClient.StagedUploadAsync(Stream content, BlobHttpHeaders blobHttpHeaders, IDictionary`2 metadata, BlobRequestConditions conditions, IProgress`1 progressHandler, Nullable`1 accessTier, Nullable`1 singleUploadThreshold, StorageTransferOptions transferOptions, Boolean async, CancellationToken cancellationToken)
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.21518.6\tools\SdkTasks\PublishArtifactsInManifest.proj(139,5): error :    at Azure.Storage.Blobs.BlobClient.UploadAsync(String path, BlobHttpHeaders httpHeaders, IDictionary`2 metadata, BlobRequestConditions conditions, IProgress`1 progressHandler, Nullable`1 accessTier, StorageTransferOptions transferOptions, CancellationToken cancellationToken)
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.21518.6\tools\SdkTasks\PublishArtifactsInManifest.proj(139,5): error :    at Azure.Storage.Blobs.BlobClient.UploadAsync(String path, Boolean overwrite, CancellationToken cancellationToken)
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.21518.6\tools\SdkTasks\PublishArtifactsInManifest.proj(139,5): error :    at Azure.Storage.Blobs.BlobClient.UploadAsync(String path, CancellationToken cancellationToken)
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.21518.6\tools\SdkTasks\PublishArtifactsInManifest.proj(139,5): error :    at Azure.Storage.Blobs.BlobClient.UploadAsync(String path)
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.21518.6\tools\SdkTasks\PublishArtifactsInManifest.proj(139,5): error :    at Microsoft.DotNet.Build.Tasks.Feed.AzureStorageAssetPublisher.PublishAssetAsync(String file, String blobPath, PushOptions options, SemaphoreSlim clientThrottle) in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/AzureStorageAssetPublisher.cs:line 48
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.21518.6\tools\SdkTasks\PublishArtifactsInManifest.proj(139,5): error :    at Microsoft.DotNet.Build.Tasks.Feed.PublishArtifactsInManifestBase.<>c__DisplayClass171_0.<<PublishAssetsUsingStreamingPublishingAsync>b__0>d.MoveNext() in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestBase.cs:line 1738
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.21518.6\tools\SdkTasks\PublishArtifactsInManifest.proj(139,5): error : --- End of stack trace from previous location ---
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.21518.6\tools\SdkTasks\PublishArtifactsInManifest.proj(139,5): error :    at Microsoft.DotNet.Build.Tasks.Feed.PublishArtifactsInManifestBase.PublishAssetsUsingStreamingPublishingAsync(IAssetPublisher assetPublisher, HashSet`1 assetsToPublish, Dictionary`2 buildAssets, TargetFeedConfig feedConfig, SemaphoreSlim clientThrottle) in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestBase.cs:line 1702
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.21518.6\tools\SdkTasks\PublishArtifactsInManifest.proj(139,5): error :    at Microsoft.DotNet.Build.Tasks.Feed.PublishArtifactsInManifestBase.PublishAssetsAsync(IAssetPublisher assetPublisher, HashSet`1 assetsToPublish, Dictionary`2 buildAssets, TargetFeedConfig feedConfig, SemaphoreSlim clientThrottle) in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestBase.cs:line 1644
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.21518.6\tools\SdkTasks\PublishArtifactsInManifest.proj(139,5): error :    at Microsoft.DotNet.Build.Tasks.Feed.PublishArtifactsInManifestBase.HandleBlobPublishingAsync(Dictionary`2 buildAssets, SemaphoreSlim clientThrottle) in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestBase.cs:line 1025
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.21518.6\tools\SdkTasks\PublishArtifactsInManifest.proj(139,5): error :    at Microsoft.DotNet.Build.Tasks.Feed.PublishArtifactsInManifestV3.ExecuteAsync() in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestV3.cs:line 187
##[error].packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.21518.6\tools\SdkTasks\PublishArtifactsInManifest.proj(139,5): error : The specified blob already exists.
```

**Comment by Evangelink** [comment]
@JoeRobich Is this issue still relevant? Everything looks green to me.

**Comment by JoeRobich** [comment]
@Evangelink Thanks. Closing it out.
