### ISSUE TITLE
Performance test failures on PRs

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/roslyn-analyzers#5790]
Performance tests failing with a message: `Could not execute because the application was not found or a compatible .NET SDK is not installed.` at `Validate Performance` step. Same faulure on many other PRs.

[More log](https://dev.azure.com/dnceng/public/_build/results?buildId=1509691&view=logs&j=c437ad79-412a-5788-29af-826e207aa5e5&t=00fb1cd8-4a81-585a-5987-c8ebcb2e642d):
```log
Running performance tests
Restoring repo at 'D:\a\1\s'
Cannot index into a null array.
Restore complete
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application 'build' does not exist.
  * You intended to execute a .NET SDK command:
      A compatible installed .NET SDK for global.json version [6.0.100] from [D:\a\1\s\global.json] was not found.
      Install the [6.0.100] .NET SDK or update [D:\a\1\s\global.json] with an installed .NET SDK:
        6.0.100-rc.1.21463.6 [D:\a\1\s\temp\perfBaseline\.dotnet\sdk]
Running tests in project 'D:\a\1\s\src\PerformanceTests\Tests\PerformanceTests.csproj'
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application 'run' does not exist.
  * You intended to execute a .NET SDK command:
      A compatible installed .NET SDK for global.json version [6.0.100] from [D:\a\1\s\global.json] was not found.
      Install the [6.0.100] .NET SDK or update [D:\a\1\s\global.json] with an installed .NET SDK:
        6.0.100-rc.1.21463.6 [D:\a\1\s\temp\perfBaseline\.dotnet\sdk]
Done with performance run
Cannot find path 'D:\a\1\s\artifacts\performance\perfResults\perfTest\results' because it does not exist.
System.Management.Automation.ItemNotFoundException: Cannot find path 'D:\a\1\s\artifacts\performance\perfResults\perfTest\results' because it does not exist.
   at System.Management.Automation.LocationGlobber.ExpandMshGlobPath(String path, Boolean allowNonexistingPaths, PSDriveInfo drive, ContainerCmdletProvider provider, CmdletProviderContext context)
   at System.Management.Automation.LocationGlobber.ResolveDriveQualifiedPath(String path, CmdletProviderContext context, Boolean allowNonexistingPaths, CmdletProvider& providerInstance)
   at System.Management.Automation.LocationGlobber.GetGlobbedMonadPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, CmdletProvider& providerInstance)
   at System.Management.Automation.PathIntrinsics.GetResolvedPSPathFromPSPath(String path, CmdletProviderContext context)
   at Microsoft.PowerShell.Commands.ResolvePathCommand.ProcessRecord()
at <ScriptBlock>, D:\a\1\s\eng\perf\ComparePerfResults.ps1: line 14
at <ScriptBlock>, D:\a\1\s\eng\perf\DiffPerfToBaseLine.ps1: line 72
at <ScriptBlock>, D:\a\1\s\eng\perf\PerfCore.ps1: line 64
at <ScriptBlock>, D:\a\_temp\408460a2-dc54-4167-8634-b93d951a33ec.ps1: line 3
at <ScriptBlock>, <No file>: line 1
```

**Comment by buyaa-n** [comment]
cc @jmarolf

**Comment by Youssef1313** [comment]
@buyaa-n I think this is now fixed and can be closed.
