### ISSUE TITLE
CSharpDetectPreviewFeatureAnalyzer hitting NullReferenceException when run on Corelib

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn-analyzers#5802]
### Analyzer

**Diagnostic ID**: [CA2252](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2252): `Opt in to preview features`

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.NetAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers)

**Version**: 6.0.3 (Latest)

### Describe the bug

e.g. AD0001 fired with the exception from the analyzer:
```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Message	AD0001	Analyzer 'Microsoft.NetCore.CSharp.Analyzers.Runtime.CSharpDetectPreviewFeatureAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
Exception occurred with following context:
Compilation: System.Private.CoreLib
ISymbol: Decimal (NamedType)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.NetCore.CSharp.Analyzers.Runtime.CSharpDetectPreviewFeatureAnalyzer.GetPreviewInterfaceNodeForTypeImplementingPreviewInterface(ISymbol typeSymbol, ISymbol previewInterfaceSymbol)
   at Microsoft.NetCore.Analyzers.Runtime.DetectPreviewFeatureAnalyzer.ProcessTypeSymbolAttributes(SymbolAnalysisContext context, ITypeSymbol symbol, ConcurrentDictionary`2 requiresPreviewFeaturesSymbols, INamedTypeSymbol previewFeatureAttributeSymbol)
   at Microsoft.NetCore.Analyzers.Runtime.DetectPreviewFeatureAnalyzer.AnalyzeSymbol(SymbolAnalysisContext context, ConcurrentDictionary`2 requiresPreviewFeaturesSymbols, IFieldSymbol virtualStaticsInInterfaces, INamedTypeSymbol previewFeatureAttributeSymbol)
   at Microsoft.NetCore.Analyzers.Runtime.DetectPreviewFeatureAnalyzer.<>c__DisplayClass33_0.<Initialize>b__2(SymbolAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteSymbolActionsCore>b__50_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: CA2252	System.Private.CoreLib		1	Active	Analyzer 'Microsoft.NetCore.CSharp.Analyzers.Runtime.CSharpDetectPreviewFeatureAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: System.Private.CoreLib
ISymbol: Decimal (NamedType)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.NetCore.CSharp.Analyzers.Runtime.CSharpDetectPreviewFeatureAnalyzer.GetPreviewInterfaceNodeForTypeImplementingPreviewInterface(ISymbol typeSymbol, ISymbol previewInterfaceSymbol)
   at Microsoft.NetCore.Analyzers.Runtime.DetectPreviewFeatureAnalyzer.ProcessTypeSymbolAttributes(SymbolAnalysisContext context, ITypeSymbol symbol, ConcurrentDictionary`2 requiresPreviewFeaturesSymbols, INamedTypeSymbol previewFeatureAttributeSymbol)
   at Microsoft.NetCore.Analyzers.Runtime.DetectPreviewFeatureAnalyzer.AnalyzeSymbol(SymbolAnalysisContext context, ConcurrentDictionary`2 requiresPreviewFeaturesSymbols, IFieldSymbol virtualStaticsInInterfaces, INamedTypeSymbol previewFeatureAttributeSymbol)
   at Microsoft.NetCore.Analyzers.Runtime.DetectPreviewFeatureAnalyzer.<>c__DisplayClass33_0.<Initialize>b__2(SymbolAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteSymbolActionsCore>b__50_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.
```
cc: @jeffhandley

**Comment by Youssef1313** [comment]
Here is a test case that will be failing

```csharp
using System;
using System.Runtime.Versioning;

partial class Program { }

partial class Program : AbClass { }

[RequiresPreviewFeatures]
public class AbClass
{
}
```
