### ISSUE TITLE
CA1836 CodeFixProvider throws NullReferenceException

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#6336]
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Text.EditorOptions.Implementation.EditorOptions.<>c.<AddDerivedOptions>b__38_0(WeakReference weakref)
   at Microsoft.VisualStudio.Utilities.FrugalList`1.RemoveAll(Predicate`1 match)
   at Microsoft.VisualStudio.Text.EditorOptions.Implementation.EditorOptions.AddDerivedOptions(EditorOptions derived)
   at Microsoft.VisualStudio.Text.EditorOptions.Implementation.EditorOptions..ctor(EditorOptions parent,IPropertyOwner scope,EditorOptionsFactoryService factory,Boolean allowsLateBinding)
   at Microsoft.VisualStudio.Text.EditorOptions.Implementation.EditorOptionsFactoryService.<>c__DisplayClass13_0.<GetOptions>b__0()
   at Microsoft.VisualStudio.Utilities.PropertyCollection.GetOrCreateSingletonProperty[T](Object key,Func`1 creator)
   at Microsoft.VisualStudio.Text.EditorOptions.Implementation.EditorOptionsFactoryService.GetOptions(IPropertyOwner scope)
   at Microsoft.VisualStudio.Text.Differencing.Implementation.DifferenceBuffer..ctor(DifferenceBufferFactoryService factory,ITextDataModel innerLeftDataModel,ITextDataModel rightDataModel,IEditorOptionsFactoryService optionsFactory,StringDifferenceOptions differenceOptions,Boolean disableEditing,Boolean wrapLeftBuffer,Boolean wrapRightBuffer,Boolean fixedBaseLeftBuffer,AsyncManualResetEvent signal)
   at Microsoft.VisualStudio.Text.Differencing.Implementation.DifferenceBufferFactoryService.CreateDifferenceBuffer(ITextBuffer baseLeftBuffer,ITextBuffer baseRightBuffer,StringDifferenceOptions options,Boolean disableEditing,Boolean wrapLeftBuffer,Boolean wrapRightBuffer)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Preview.AbstractPreviewFactoryService`1.CreateNewDifferenceViewerAsync[TDifferenceViewer](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Preview.AbstractPreviewFactoryService`1.CreateChangedDocumentViewAsync[TDifferenceViewer](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Preview.AbstractPreviewFactoryService`1.CreateChangedDocumentPreviewViewAsync[TDifferenceViewer](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Preview.AbstractPreviewFactoryService`1.<>c__DisplayClass11_1.<GetSolutionPreviews>b__0[TDifferenceViewer](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.SolutionPreviewResult.GetPreviewsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

Code I had:

```csharp
using System;
using System.Collections.Concurrent;
using System.Linq;

var queue = new ConcurrentQueue<string>();
queue.Enqueue("test");

if (queue.Count > 0)
{
    // test
}
```

The codefix was offered correctly once, but subsequent invocations of lighbulb shows the above exception.

**Comment by Youssef1313** [comment]
This might not be related to CA1836 specifically.

**Comment by Youssef1313** [comment]
I reported to Developer Community so that all needed logs are available (dumps, traces, etc).

https://developercommunity.visualstudio.com/t/NullReferenceException-when-invoking-lig/10228158

Closing this one.
