### ISSUE TITLE
NullReferenceException from CA1861

### ISSUE THREAD

**Issue by jnyrup** [dotnet/roslyn-analyzers#6686]
### Analyzer

**Diagnostic ID**: [CA1861](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1861): `Avoid constant arrays as arguments`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 8 Preview 5 SDK](https://learn.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [8.0.100-preview.5.23303.2](https://dotnet.microsoft.com/download/dotnet/8.0)

### Describe the bug

When running analysis on the snippet below I get
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	AD0001	Analyzer 'Microsoft.NetCore.Analyzers.Runtime.AvoidConstArraysAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
Exception occurred with following context:
Compilation: ClassLibrary8
IOperation: ArrayCreation
SyntaxTree: C:\dev\repos\ClassLibrary8\ClassLibrary8\Class1.cs
SyntaxNode: new object[0] [ArrayCreationExpressionSyntax]@[166..179) (9,10)-(9,23)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.NetCore.Analyzers.Runtime.AvoidConstArraysAnalyzer.<>c__DisplayClass5_0.<Initialize>b__1(OperationAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteOperationAction>b__50_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info, CancellationToken cancellationToken)
-----

Suppress the following diagnostics to disable this analyzer: CA1861	ClassLibrary8	C:\dev\repos\ClassLibrary8\ClassLibrary8\ClassLibrary8.csproj	1	Active

```

### Steps To Reproduce

```cs
using System;
using System.Collections;

namespace ClassLibrary8;

public static class MyClass
{
    public static TheoryData Cases => new()
    {
        { new object[0] }
    };
}

public class TheoryData : IEnumerable
{
    public void Add(object _) { }

    IEnumerator IEnumerable.GetEnumerator() => throw new NotImplementedException();
}
```

### Expected behavior
There should not be an AD0001 in the Error List

### Actual behavior
There is an AD0001 in the Error List

**Comment by Evangelink** [comment]
Hi @mavasani,

I am starting to face this issue on our projects. This seems to correlate with the upgrade of `Microsoft.Net.Compilers.Toolset` package from arcade.

```csharp
public TestObjectConverter7()
    {
        TestPropertyCtor = typeof(TestProperty).GetConstructor(BindingFlags.NonPublic | BindingFlags.Instance, null, new Type[0], null);
    }
```

error

```
Error	AD0001	Analyzer 'Microsoft.NetCore.Analyzers.Runtime.AvoidConstArraysAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
Exception occurred with following context:
Compilation: Microsoft.TestPlatform.CommunicationUtilities
IOperation: ArrayCreation
SyntaxTree: C:\src\vstest\src\Microsoft.TestPlatform.CommunicationUtilities\Serialization\TestObjectConverter.cs
SyntaxNode: new Type[0] [ArrayCreationExpressionSyntax]@[4004..4015) (109,117)-(109,128)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.NetCore.Analyzers.Runtime.AvoidConstArraysAnalyzer.<>c__DisplayClass5_0.<Initialize>b__1(OperationAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteOperationAction>b__50_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info, CancellationToken cancellationToken)
```

Is it just waiting for deployment?

**Comment by mavasani** [comment]
@Evangelink - that is correct. Can you try the latest preview NuGet package: https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet8/NuGet/Microsoft.CodeAnalysis.NetAnalyzers/overview/8.0.0-preview.23360.1?

**Comment by Evangelink** [comment]
@mavasani I confirm that works by manually referencing this package. Are analyzers only inserted in SDK or also in VS? For the SDK, do you know in which preview they will get shipped (we current use 8.0.100-preview.5.23303.2 - https://github.com/microsoft/vstest/blob/main/global.json#L3)

**Comment by mavasani** [comment]
> Are analyzers only inserted in SDK or also in VS? For the SDK, do you know in which preview they will get shipped

@buyaa-n?

**Comment by buyaa-n** [comment]
The fix doesn't look like [made it into SDK preview 5](https://github.com/dotnet/sdk/blame/release/8.0.1xx-preview5/eng/Versions.props#L96), though it does look [updated in SDK preview 6](https://github.com/dotnet/sdk/blob/release/8.0.1xx-preview6/eng/Versions.props#L96)
