### ISSUE TITLE
.ApiDesignGuidelines.BasicOverrideEqualsOnOverloadingOperatorEqualsAnalyzer throws NRE in Roslyn.sln

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn-analyzers#6778]
```
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	AD0001	Analyzer 'Microsoft.CodeQuality.VisualBasic.Analyzers.ApiDesignGuidelines.BasicOverrideEqualsOnOverloadingOperatorEqualsAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: Roslyn.Compilers.VisualBasic.IOperation.UnitTests
ISymbol: ExpectedSymbolVerifier (NamedType)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeQuality.VisualBasic.Analyzers.ApiDesignGuidelines.BasicOverrideEqualsOnOverloadingOperatorEqualsAnalyzer.HasEqualityOperator(INamedTypeSymbol type)
   at Microsoft.CodeQuality.VisualBasic.Analyzers.ApiDesignGuidelines.BasicOverrideEqualsOnOverloadingOperatorEqualsAnalyzer._Closure$__._Lambda$__7-0(SymbolAnalysisContext symbolContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info, CancellationToken cancellationToken)
-----
'.	Roslyn.Compilers.VisualBasic.IOperation.UnitTests (net472)	D:\R3\src\Compilers\VisualBasic\Test\IOperation\Roslyn.Compilers.VisualBasic.IOperation.UnitTests.vbproj	1	
```

**Comment by mavasani** [comment]
Interesting.. the method has following implementation: https://github.com/dotnet/roslyn-analyzers/blob/20690b42777d89aade8323b103f61893091c1dca/src/NetAnalyzers/VisualBasic/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/BasicOverrideEqualsOnOverloadingOperatorEquals.vb#L63-L74

Does `?.` operator in VB not work the way I think it should?

**Comment by mavasani** [comment]
Verified with a simple console app that VB that the below can indeed throw an NRE in VB as the second part of the condition gets executed even when `method` is null:

```vb
   If method?.MethodKind = MethodKind.UserDefinedOperator AndAlso 
             CaseInsensitiveComparison.Equals(method.Name, WellKnownMemberNames.EqualityOperatorName) Then
```
