### ISSUE TITLE
IntelliSense propsal to avoid returning empty Arrays causes an error in Visual Studio

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn-analyzers#7021]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/IntelliSense-propsal-to-avoid-returning-/10504004)._

---
[severity:It bothers me. A fix would be nice]

_Environment_
I have a .NET 7.0 VB.NET-project (either console or WinForms) in Visual Studio Version Version 17.8.0 Preview 5.0 on a 64-bit Win10 PC.

**Problem**
An IntelliSense proposal causes a Visual Studio error. This proposal won't be shown in an .NET framework project.

**Description**
I have the following code:

```
Private Function Foo() As IEnumerable(Of String)
	Return {}
End Function
```
IntelliSense tells me, that there is a better way. If I let me show the proposals, it says: I shouldn't return `{}`, but instead `Array.Empty(Of String)`. But there is also an error that occured in Visual Studio:
![VisualStudioError.png](https://aka.ms/dc/image?name=Ba58e1a74f00b4dcc843bd84d8264a879638343488119579735_VisualStudioError.png&tid=a58e1a74f00b4dcc843bd84d8264a879638343488119579735)

The stack trace:

```
System.InvalidCastException : Das Objekt des Typs "ConstructedInstanceType" kann nicht in Typ "Microsoft.CodeAnalysis.IArrayTypeSymbol" umgewandelt werden.
   at Microsoft.NetCore.Analyzers.Runtime.AvoidZeroLengthArrayAllocationsFixer.GetArrayElementType(SyntaxNode arrayCreationExpression,SemanticModel semanticModel,CancellationToken cancellationToken)
   at async Microsoft.NetCore.Analyzers.Runtime.AvoidZeroLengthArrayAllocationsFixer.ConvertToArrayEmptyAsync(<Unbekannte Parameter>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.NetCore.Analyzers.Runtime.AvoidZeroLengthArrayAllocationsFixer.<>c__DisplayClass4_0.<RegisterCodeFixesAsync>b__0(<Unbekannte Parameter>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unbekannte Parameter>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unbekannte Parameter>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unbekannte Parameter>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unbekannte Parameter>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.PreviewChangesSuggestedAction.CreateAsync(<Unbekannte Parameter>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.GetPreviewChangesFlavorAsync(<Unbekannte Parameter>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.CreateAllFlavorsAsync(<Unbekannte Parameter>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unbekannte Parameter>)
```

**Consequences**
I feel annoyed.

---
#### Feedback Bot on 10/31/2023, 10:10 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by VaporiZed** [comment]
Well, my image seems to be missing in the start post.
In the case you need it:
![VisualStudioError](https://github.com/dotnet/roslyn-analyzers/assets/49878115/4e7797c5-2a89-49c4-833c-53262273baac)
