### ISSUE TITLE
Analyzer 'Desktop.Analyzers.TypesShouldNotExtendCertainBaseTypesAnalyzer' threw an exception of type 'System.ArgumentNullException' with message 'Value cannot be null. Parameter name: item'.

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#854]
1. Clean RoslynDev hive on your machine
2. Get latest sources of roslyn and build
3. Get latest sources of roslyn-analyzers and build
4. devenv /rootsuffix RoslynDev
5. Open Roslyn.sln

Got the following AD0001 in the error list:
```
Severity	Code	Description	Project	File	Line	Source	Tool	Detail Description
Error	AD0001	Analyzer 'Desktop.Analyzers.TypesShouldNotExtendCertainBaseTypesAnalyzer' threw an exception of type 'System.ArgumentNullException' with message 'Value cannot be null.
Parameter name: item'.	CSharpScriptingTest		1	IntelliSense	Desktop.Analyzers	Analyzer 'Desktop.Analyzers.TypesShouldNotExtendCertainBaseTypesAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: Microsoft.CodeAnalysis.CSharp.Scripting.UnitTests
ISymbol: I (NamedType)

System.ArgumentNullException: Value cannot be null.
Parameter name: item
   at System.Collections.Immutable.ImmutableHashSet`1.Contains(T item)
   at Desktop.Analyzers.TypesShouldNotExtendCertainBaseTypesAnalyzer.<>c__DisplayClass8_0.<AnalyzeCompilationStart>b__2(SymbolAnalysisContext saContext) in c:\roslyn-analyzers\src\Desktop.Analyzers\Core\TypesShouldNotExtendCertainBaseTypes.cs:line 66
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass37_0.<ExecuteSymbolActionsCore>b__0()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info)
-----
'.
```

**Comment by mavasani** [comment]
This was fixed by 3af1625c
